var SC_value=[
    {'pid': '7901', 'name': 'ベースクレイ', 'kind': '其他', 'obtain': '0', 'mappic': '2', 'sfrom': '全采集物'},
    {'pid': '7902', 'name': '力の結晶片G1', 'kind': '其他', 'obtain': '0', 'mappic': '2', 'sfrom': '植物、矿物'},
    {'pid': '7903', 'name': '持続の結晶片G1', 'kind': '其他', 'obtain': '0', 'mappic': '2', 'sfrom': '植物、矿物'},
    {'pid': '7904', 'name': '世話役の結晶片G1', 'kind': '其他', 'obtain': '0', 'mappic': '2', 'sfrom': '植物、矿物'},
    {'pid': '7905', 'name': '世話役の結晶片G2', 'kind': '其他', 'obtain': '0', 'mappic': '2', 'sfrom': '植物、矿物'},
    {'pid': '7006', 'name': 'トコヨ草', 'obtain': '0', 'kind': '植物采集', 'mappic': '2', 'sfrom': '植物'},
    {'pid': '7007', 'name': 'グロークンシード', 'obtain': '0', 'kind': '植物采集', 'mappic': '2', 'sfrom': '植物'},
    {'pid': '7008', 'name': 'あかつき草', 'obtain': 'fld001', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 148},
    {'pid': '7009', 'name': '長毛草', 'obtain': 'fld001', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 147},
    {'pid': '7010', 'name': '星屑草', 'obtain': 'fld001', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 149},
    {'pid': '7011', 'name': '煙霧苔', 'obtain': 'fld002', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 114},
    {'pid': '7012', 'name': 'ストリガの実', 'obtain': 'fld002', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 115},
    {'pid': '7013', 'name': '道草花', 'obtain': 'fld003', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 129},
    {'pid': '7014', 'name': 'メリソスフラワー', 'obtain': 'fld003', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 127},
    {'pid': '7015', 'name': '寂れユリ', 'obtain': 'fld003', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 128},
    {'pid': '7016', 'name': '砂丘斑点虫', 'obtain': 'fld004', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 249},
    {'pid': '7017', 'name': 'レインフォールハーブ', 'obtain': 'fld004', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 251},
    {'pid': '7018', 'name': '砂ミミズ', 'obtain': 'fld004', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 248},
    {'pid': '7019', 'name': '砂蝋枝', 'obtain': 'fld004', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 250},
    {'pid': '7020', 'name': 'ミラービーンズ', 'obtain': 'fld004', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 247},
    {'pid': '7021', 'name': 'リュウノツメモドキ', 'obtain': 'dng009', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 22},
    {'pid': '7022', 'name': '燃える妖花', 'obtain': 'dng009', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 23},
    {'pid': '7023', 'name': 'フィエルの若木', 'obtain': 'pub0802', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 28},
    {'pid': '7024', 'name': '静寂草', 'obtain': 'dng004', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 26},
    {'pid': '7025', 'name': 'オイルシェールグラス', 'obtain': 'pub0102', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 19},
    {'pid': '7026', 'name': 'ドーンマッシュルーム', 'obtain': 'dng015', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 24},
    {'pid': '7027', 'name': 'メンヨウ草', 'obtain': 'pub0805', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 31},
    {'pid': '7028', 'name': '半島カナムグラ', 'obtain': 'fld005', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 118},
    {'pid': '7029', 'name': '氷点花', 'obtain': 'fld005', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 116},
    {'pid': '7030', 'name': 'カムノキの新芽', 'obtain': 'fld005', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 117},
    {'pid': '7031', 'name': 'ドラファーフ草', 'obtain': 'pub0902', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 20},
    {'pid': '7032', 'name': '山麓ナデシコ', 'obtain': 'pub0202', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 17},
    {'pid': '7033', 'name': 'クロネッタの果実', 'obtain': 'pub0806', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 23},
    {'pid': '7034', 'name': 'トンネルヨモギ', 'obtain': 'pub0206', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 17},
    {'pid': '7035', 'name': 'スナリプル草', 'obtain': 'pub0903', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 30},
    {'pid': '7036', 'name': '高嶺バッタ', 'obtain': 'pub0103', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 20},
    {'pid': '7037', 'name': 'リゾートヤシの葉', 'obtain': 'fld006', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 133},
    {'pid': '7038', 'name': 'スレンダーグリーン', 'obtain': 'fld006', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 134},
    {'pid': '7039', 'name': 'ルインドプラント', 'obtain': 'pub0106', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 20},
    {'pid': '7040', 'name': '夜明かり花', 'obtain': 'pub0807', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 31},
    {'pid': '7041', 'name': 'アルストンシャープ', 'obtain': 'pub0108', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 18},
    {'pid': '7042', 'name': 'プアナリリウム', 'obtain': 'fld007', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 98},
    {'pid': '7043', 'name': 'ロカヒ材木', 'obtain': 'fld007', 'kind': '植物采集', 'mappic': '1', 'sfrom': '植物', 'Point': 97},
    {'pid': '7207', 'name': '水晶の原石', 'kind': '矿物采集', 'obtain': '0', 'mappic': '2', 'sfrom': '矿物'},
    {'pid': '7208', 'name': '環状石', 'kind': '矿物采集', 'obtain': '0', 'mappic': '2', 'sfrom': '矿物'},
    {'pid': '7209', 'name': '平原ヒスイ', 'kind': '矿物采集', 'obtain': 'fld001', 'mappic': '1', 'sfrom': '矿物', 'Point': 146},
    {'pid': '7210', 'name': 'アステリウム鉱石', 'kind': '矿物采集', 'obtain': 'fld001', 'mappic': '1', 'sfrom': '矿物', 'Point': 144},
    {'pid': '7211', 'name': 'ジラ輝石', 'kind': '矿物采集', 'obtain': 'fld001', 'mappic': '1', 'sfrom': '矿物', 'Point': 143},
    {'pid': '7212', 'name': '隕鉄の欠片', 'kind': '矿物采集', 'obtain': 'fld001', 'mappic': '1', 'sfrom': '矿物', 'Point': 145},
    {'pid': '7213', 'name': 'バハ鉱石', 'kind': '矿物采集', 'obtain': 'fld002', 'mappic': '1', 'sfrom': '矿物', 'Point': 113},
    {'pid': '7214', 'name': '静夜鉱', 'kind': '矿物采集', 'obtain': 'fld002', 'mappic': '1', 'sfrom': '矿物', 'Point': 111},
    {'pid': '7215', 'name': '湧水石', 'kind': '矿物采集', 'obtain': 'fld002', 'mappic': '1', 'sfrom': '矿物', 'Point': 112},
    {'pid': '7216', 'name': 'モンテノールストーン', 'kind': '矿物采集', 'obtain': 'fld003', 'mappic': '1', 'sfrom': '矿物', 'Point': 126},
    {'pid': '7217', 'name': 'メリソス石灰石', 'kind': '矿物采集', 'obtain': 'fld003', 'mappic': '1', 'sfrom': '矿物', 'Point': 125},
    {'pid': '7218', 'name': 'エバーグリーン雲母砂', 'kind': '矿物采集', 'obtain': 'fld004', 'mappic': '1', 'sfrom': '矿物', 'Point': 244},
    {'pid': '7219', 'name': '雨唄いの化石', 'kind': '矿物采集', 'obtain': 'fld004', 'mappic': '1', 'sfrom': '矿物', 'Point': 246},
    {'pid': '7220', 'name': '谷底白砂', 'kind': '矿物采集', 'obtain': 'fld004', 'mappic': '1', 'sfrom': '矿物', 'Point': 243},
    {'pid': '7221', 'name': '風の這痕', 'kind': '矿物采集', 'obtain': 'fld004', 'mappic': '1', 'sfrom': '矿物', 'Point': 245},
    {'pid': '7222', 'name': '砂丘生痕', 'kind': '矿物采集', 'obtain': 'fld004', 'mappic': '1', 'sfrom': '矿物', 'Point': 242},
    {'pid': '7223', 'name': '哭竜鉱', 'kind': '矿物采集', 'obtain': 'dng009', 'mappic': '1', 'sfrom': '矿物', 'Point': 20},
    {'pid': '7224', 'name': '翼竜の化石', 'kind': '矿物采集', 'obtain': 'dng009', 'mappic': '1', 'sfrom': '矿物', 'Point': 21},
    {'pid': '7225', 'name': '風故物', 'kind': '矿物采集', 'obtain': 'pub0801', 'mappic': '1', 'sfrom': '矿物', 'Point': 27},
    {'pid': '7226', 'name': 'ボルオム鉛', 'kind': '矿物采集', 'obtain': 'pub0201', 'mappic': '1', 'sfrom': '矿物', 'Point': 15},
    {'pid': '7227', 'name': '落星孔雀石', 'kind': '矿物采集', 'obtain': 'pub0802', 'mappic': '1', 'sfrom': '矿物', 'Point': 27},
    {'pid': '7228', 'name': '硬化プレート', 'kind': '矿物采集', 'obtain': 'pub0803', 'mappic': '1', 'sfrom': '矿物', 'Point': 22},
    {'pid': '7229', 'name': '謎の金属', 'kind': '矿物采集', 'obtain': 'dng007', 'mappic': '1', 'sfrom': '矿物', 'Point': 24},
    {'pid': '7230', 'name': '盛時の礫塊', 'kind': '矿物采集', 'obtain': 'dng004', 'mappic': '1', 'sfrom': '矿物', 'Point': 25},
    {'pid': '7231', 'name': '風止みの遺物', 'kind': '矿物采集', 'obtain': 'pub0901', 'mappic': '1', 'sfrom': '矿物', 'Point': 28},
    {'pid': '7232', 'name': '浮かぶ車輪', 'kind': '矿物采集', 'obtain': 'pub0804', 'mappic': '1', 'sfrom': '矿物', 'Point': 24},
    {'pid': '7233', 'name': '星状輝石', 'kind': '矿物采集', 'obtain': 'pub0102', 'mappic': '1', 'sfrom': '矿物', 'Point': 18},
    {'pid': '7234', 'name': 'アミメバチ', 'kind': '矿物采集', 'obtain': 'dng015', 'mappic': '1', 'sfrom': '矿物', 'Point': 23},
    {'pid': '7235', 'name': '曇天結晶', 'kind': '矿物采集', 'obtain': 'pub0805', 'mappic': '1', 'sfrom': '矿物', 'Point': 30},
    {'pid': '7236', 'name': 'ミダイエ鉱', 'kind': '矿物采集', 'obtain': 'fld005', 'mappic': '1', 'sfrom': '矿物', 'Point': 115},
    {'pid': '7237', 'name': 'アイアンヘルムの破片', 'kind': '矿物采集', 'obtain': 'fld005', 'mappic': '1', 'sfrom': '矿物', 'Point': 113},
    {'pid': '7238', 'name': 'オルドナイト', 'kind': '矿物采集', 'obtain': 'fld005', 'mappic': '1', 'sfrom': '矿物', 'Point': 114},
    {'pid': '7239', 'name': 'アランダル歯車', 'kind': '矿物采集', 'obtain': 'pub0902', 'mappic': '1', 'sfrom': '矿物', 'Point': 19},
    {'pid': '7240', 'name': 'インボルナイト', 'kind': '矿物采集', 'obtain': 'pub0202', 'mappic': '1', 'sfrom': '矿物', 'Point': 16},
    {'pid': '7241', 'name': 'スピンドルパーツ', 'kind': '矿物采集', 'obtain': 'pub0206', 'mappic': '1', 'sfrom': '矿物', 'Point': 16},
    {'pid': '7242', 'name': 'モスメタル', 'kind': '矿物采集', 'obtain': 'pub0806', 'mappic': '1', 'sfrom': '矿物', 'Point': 22},
    {'pid': '7243', 'name': 'サイコロ晶体', 'kind': '矿物采集', 'obtain': 'pub0903', 'mappic': '1', 'sfrom': '矿物', 'Point': 29},
    {'pid': '7244', 'name': 'ジャイロディスク', 'kind': '矿物采集', 'obtain': 'pub0103', 'mappic': '1', 'sfrom': '矿物', 'Point': 19},
    {'pid': '7245', 'name': 'スターサンド', 'kind': '矿物采集', 'obtain': 'fld006', 'mappic': '1', 'sfrom': '矿物', 'Point': 131},
    {'pid': '7246', 'name': '分かれた輝石', 'kind': '矿物采集', 'obtain': 'fld006', 'mappic': '1', 'sfrom': '矿物', 'Point': 132},
    {'pid': '7247', 'name': 'ゴーストストーン', 'kind': '矿物采集', 'obtain': 'pub0106', 'mappic': '1', 'sfrom': '矿物', 'Point': 19},
    {'pid': '7248', 'name': 'スクラップシャフト', 'kind': '矿物采集', 'obtain': 'pub0505', 'mappic': '1', 'sfrom': '矿物', 'Point': 22},
    {'pid': '7249', 'name': 'カースドストーン', 'kind': '矿物采集', 'obtain': 'pub0302', 'mappic': '1', 'sfrom': '矿物', 'Point': 18},
    {'pid': '7250', 'name': '月明かりの樹結晶', 'kind': '矿物采集', 'obtain': 'pub0807', 'mappic': '1', 'sfrom': '矿物', 'Point': 30},
    {'pid': '7251', 'name': '鉱割石', 'kind': '矿物采集', 'obtain': 'pub0108', 'mappic': '1', 'sfrom': '矿物', 'Point': 17},
    {'pid': '7252', 'name': '海積層石', 'kind': '矿物采集', 'obtain': 'pub0604', 'mappic': '1', 'sfrom': '矿物', 'Point': 31},
    {'pid': '7253', 'name': 'つややかな古来石', 'kind': '矿物采集', 'obtain': 'pub0301', 'mappic': '1', 'sfrom': '矿物', 'Point': 19},
    {'pid': '7254', 'name': '防水機械片', 'kind': '矿物采集', 'obtain': 'pub0506', 'mappic': '1', 'sfrom': '矿物', 'Point': 25},
    {'pid': '7255', 'name': 'プナのさざれ石', 'kind': '矿物采集', 'obtain': 'fld007', 'mappic': '1', 'sfrom': '矿物', 'Point': 96},
    {'pid': '7401', 'name': '割れた貝殻', 'kind': '水栖采集', 'obtain': '0', 'mappic': '2', 'sfrom': '水栖'},
    {'pid': '7402', 'name': 'さざなみ石', 'kind': '水栖采集', 'obtain': '0', 'mappic': '2', 'sfrom': '水栖'},
    {'pid': '7403', 'name': '旅藻草', 'kind': '水栖采集', 'obtain': 'fld001', 'mappic': '1', 'sfrom': '水栖', 'Point': 150},
    {'pid': '7404', 'name': 'フィエル蓮葉', 'kind': '水栖采集', 'obtain': 'fld002', 'mappic': '1', 'sfrom': '水栖', 'Point': 116},
    {'pid': '7405', 'name': 'リッツェホーンウッド', 'kind': '水栖采集', 'obtain': 'fld003', 'mappic': '1', 'sfrom': '水栖', 'Point': 132},
    {'pid': '7406', 'name': '急流藻草', 'kind': '水栖采集', 'obtain': 'fld003', 'mappic': '1', 'sfrom': '水栖', 'Point': 130},
    {'pid': '7407', 'name': 'モンテノール池苔', 'kind': '水栖采集', 'obtain': 'fld003', 'mappic': '1', 'sfrom': '水栖', 'Point': 131},
    {'pid': '7408', 'name': '海蛇草', 'kind': '水栖采集', 'obtain': 'fld005', 'mappic': '1', 'sfrom': '水栖', 'Point': 120},
    {'pid': '7409', 'name': 'ランツェウッド', 'kind': '水栖采集', 'obtain': 'fld005', 'mappic': '1', 'sfrom': '水栖', 'Point': 119},
    {'pid': '7410', 'name': '常夏巻貝', 'kind': '水栖采集', 'obtain': 'fld006', 'mappic': '1', 'sfrom': '水栖', 'Point': 135},
    {'pid': '7411', 'name': 'サンセットプラント', 'kind': '水栖采集', 'obtain': 'fld006', 'mappic': '1', 'sfrom': '水栖', 'Point': 136},
    {'pid': '7412', 'name': 'マダラガイ', 'kind': '水栖采集', 'obtain': 'fld006', 'mappic': '1', 'sfrom': '水栖', 'Point': 137},
    {'pid': '7413', 'name': '入江穴貝', 'kind': '水栖采集', 'obtain': 'pub0604', 'mappic': '1', 'sfrom': '水栖', 'Point': 32},
    {'pid': '7414', 'name': 'ワイオリの土', 'kind': '水栖采集', 'obtain': 'fld007', 'mappic': '1', 'sfrom': '水栖', 'Point': 99},
    {'pid': '7501', 'name': '動的エングラムの欠片', 'kind': '小怪掉落', 'obtain': '0', 'mappic': '0', 'sfrom': '任意小怪'},
    {'pid': '7502', 'name': '動的エングラム結晶片', 'kind': '小怪掉落', 'obtain': '0', 'mappic': '0', 'sfrom': '任意小怪'},
    {'pid': '7503', 'name': '火精の結晶片G1', 'kind': '小怪掉落', 'obtain': '0', 'mappic': '0', 'sfrom': '对应属性小怪'},
    {'pid': '7504', 'name': '氷精の結晶片G1', 'kind': '小怪掉落', 'obtain': '0', 'mappic': '0', 'sfrom': '对应属性小怪'},
    {'pid': '7505', 'name': '雷精の結晶片G1', 'kind': '小怪掉落', 'obtain': '0', 'mappic': '0', 'sfrom': '对应属性小怪'},
    {'pid': '7506', 'name': '土精の結晶片G1', 'kind': '小怪掉落', 'obtain': '0', 'mappic': '0', 'sfrom': '对应属性小怪'},
    {'pid': '7507', 'name': 'グレートファングの研がれた牙', 'kind': '小怪掉落', 'obtain': 'fld004', 'mappic': '4', 'sfrom': 'グレートファング', 'map': 'レインフォール旧街道'},
    {'pid': '7508', 'name': 'タイラントボア・グロウの上質な毛皮', 'kind': '小怪掉落', 'obtain': 'fld001', 'mappic': '4', 'sfrom': 'タイラントボア・グロウ', 'map': '夕凪の段丘'},
    {'pid': '7509', 'name': 'ランブルボアの爪', 'kind': '小怪掉落', 'obtain': 'fld001', 'mappic': '4', 'sfrom': 'ランブルボア', 'map': 'アンドラ盆地'},
    {'pid': '7510', 'name': 'デザートファングの高品質な毛皮', 'kind': '小怪掉落', 'obtain': 'fld004', 'mappic': '4', 'sfrom': 'デザートファング', 'map': 'レインフォール旧街道'},
    {'pid': '7511', 'name': 'デザートファングの尖った爪', 'kind': '小怪掉落', 'obtain': 'fld004', 'mappic': '4', 'sfrom': 'デザートファング', 'map': '風止みの荒地'},
    {'pid': '7512', 'name': 'ウリボの尾', 'kind': '小怪掉落', 'obtain': 'fld001', 'mappic': '4', 'sfrom': 'ウリボ', 'map': '海鳴りの草原'},
    {'pid': '7513', 'name': 'ホーンゴートの角', 'kind': '小怪掉落', 'obtain': 'fld002', 'mappic': '4', 'sfrom': 'ホーンゴート', 'map': '神の見守る丘'},
    {'pid': '7514', 'name': 'ホーンゴートの毛皮', 'kind': '小怪掉落', 'obtain': 'fld002', 'mappic': '4', 'sfrom': 'ホーンゴート', 'map': 'フィエル嶺水池'},
    {'pid': '7515', 'name': 'カイザーエルクの毛皮', 'kind': '小怪掉落', 'obtain': 'fld002', 'mappic': '4', 'sfrom': 'カイザーエルク', 'map': '神の見守る丘'},
    {'pid': '7516', 'name': 'ランドフォックスの尻尾', 'kind': '小怪掉落', 'obtain': 'fld001', 'mappic': '4', 'sfrom': 'ランドフォックス', 'map': 'ミンスター丘陵'},
    {'pid': '7517', 'name': 'ハイランドフォックスの爪', 'kind': '小怪掉落', 'obtain': 'fld002', 'mappic': '4', 'sfrom': 'ハイランドフォックス', 'map': '鎮まりの山麓'},
    {'pid': '7518', 'name': 'ハイランドフォックスの牙', 'kind': '小怪掉落', 'obtain': 'fld002', 'mappic': '4', 'sfrom': 'ハイランドフォックス', 'map': '神の見守る丘'},
    {'pid': '7519', 'name': 'ランドホークの穿孔嘴', 'kind': '小怪掉落', 'obtain': 'fld004', 'mappic': '4', 'sfrom': 'ランドホーク', 'map': '帰らずの砂塵'},
    {'pid': '7520', 'name': 'ランドホークの鉤爪', 'kind': '小怪掉落', 'obtain': 'fld004', 'mappic': '4', 'sfrom': 'ランドホーク', 'map': 'オルビド平野'},
    {'pid': '7521', 'name': 'ゴブリンの棍棒', 'kind': '小怪掉落', 'obtain': 'fld001', 'mappic': '4', 'sfrom': 'ゴブリン', 'map': 'アンドラ盆地'},
    {'pid': '7522', 'name': 'ゴブリンのたてがみ', 'kind': '小怪掉落', 'obtain': 'fld002', 'mappic': '4', 'sfrom': 'ゴブリン', 'map': '鎮まりの山麓'},
    {'pid': '7523', 'name': 'ゴブリンの尻尾', 'kind': '小怪掉落', 'obtain': 'fld002', 'mappic': '4', 'sfrom': 'ゴブリン', 'map': 'フィエル嶺水池'},
    {'pid': '7524', 'name': 'ゴブリンのキバ', 'kind': '小怪掉落', 'obtain': 'dng009', 'mappic': '4', 'sfrom': 'ゴブリン'},
    {'pid': '7525', 'name': 'エルダーゴブリンの杖', 'kind': '小怪掉落', 'obtain': 'fld001', 'mappic': '4', 'sfrom': 'エルダーゴブリン', 'map': '夕凪の段丘'},
    {'pid': '7526', 'name': 'エルダーゴブリンの首飾り', 'kind': '小怪掉落', 'obtain': 'fld002', 'mappic': '4', 'sfrom': 'エルダーゴブリン', 'map': '鎮まりの山麓'},
    {'pid': '7527', 'name': 'ゴブリンウォーリアーのたてがみ', 'kind': '小怪掉落', 'obtain': 'fld002', 'mappic': '4', 'sfrom': 'ゴブリンウォーリアー', 'map': '鎮まりの山麓'},
    {'pid': '7528', 'name': 'ゴブリンウォーリアーの尖った爪', 'kind': '小怪掉落', 'obtain': 'fld002', 'mappic': '4', 'sfrom': 'ゴブリンウォーリアー', 'map': 'フィエル嶺水池'},
    {'pid': '7529', 'name': 'ゴブリンセージの杖', 'kind': '小怪掉落', 'obtain': 'pub0802', 'mappic': '4', 'sfrom': 'ゴブリンセージ'},
    {'pid': '7530', 'name': 'ムークの頸毛', 'kind': '小怪掉落', 'obtain': 'fld003', 'mappic': '4', 'sfrom': 'ムーク', 'map': 'リッツェ交易街道'},
    {'pid': '7531', 'name': 'ムークの鉤爪', 'kind': '小怪掉落', 'obtain': 'fld003', 'mappic': '4', 'sfrom': 'ムーク', 'map': 'メリソス川流域'},
    {'pid': '7532', 'name': 'ムークの爪', 'kind': '小怪掉落', 'obtain': 'pub0801', 'mappic': '4', 'sfrom': 'ムーク'},
    {'pid': '7533', 'name': 'ムークアーチャーのキバ', 'kind': '小怪掉落', 'obtain': 'fld003', 'mappic': '4', 'sfrom': 'ムークアーチャー', 'map': 'メリソス川流域'},
    {'pid': '7534', 'name': 'オーガの重角', 'kind': '小怪掉落', 'obtain': 'fld001', 'mappic': '4', 'sfrom': 'オーガ', 'map': '夕凪の段丘'},
    {'pid': '7535', 'name': 'ドゴルマンの体毛', 'kind': '小怪掉落', 'obtain': 'fld004', 'mappic': '4', 'sfrom': 'ドゴルマン', 'map': '帰らずの砂塵'},
    {'pid': '7536', 'name': 'ミーンの羽', 'kind': '小怪掉落', 'obtain': 'fld003', 'mappic': '4', 'sfrom': 'ミーン', 'map': 'リッツェ交易街道'},
    {'pid': '7537', 'name': 'ミーンの針', 'kind': '小怪掉落', 'obtain': 'fld003', 'mappic': '4', 'sfrom': 'ミーン', 'map': 'ガレィリッジ廃道'},
    {'pid': '7538', 'name': 'ミーンの丸殻', 'kind': '小怪掉落', 'obtain': 'pub0801', 'mappic': '4', 'sfrom': 'ミーン'},
    {'pid': '7539', 'name': 'サンドバイパーの甲殻', 'kind': '小怪掉落', 'obtain': 'fld004', 'mappic': '4', 'sfrom': 'サンドバイパー', 'map': 'レインフォール旧街道'},
    {'pid': '7540', 'name': 'サンドバイパーの殻', 'kind': '小怪掉落', 'obtain': 'fld004', 'mappic': '4', 'sfrom': 'サンドバイパー', 'map': '陽炎の谷'},
    {'pid': '7541', 'name': 'サンドバイパーの棘', 'kind': '小怪掉落', 'obtain': 'fld004', 'mappic': '4', 'sfrom': 'サンドバイパー', 'map': '風止みの荒地'},
    {'pid': '7542', 'name': 'サンドバイパーのテール', 'kind': '小怪掉落', 'obtain': 'fld004', 'mappic': '4', 'sfrom': 'サンドバイパー', 'map': 'オルビド平野'},
    {'pid': '7543', 'name': 'シャドウバイパーの立派な殻', 'kind': '小怪掉落', 'obtain': 'fld004', 'mappic': '4', 'sfrom': 'シャドウバイパー', 'map': 'レインフォール旧街道'},
    {'pid': '7544', 'name': 'シャドウバイパーのロングテール', 'kind': '小怪掉落', 'obtain': 'fld004', 'mappic': '4', 'sfrom': 'シャドウバイパー', 'map': '陽炎の谷'},
    {'pid': '7545', 'name': 'シャドウバイパーの厚手の外皮', 'kind': '小怪掉落', 'obtain': 'fld004', 'mappic': '4', 'sfrom': 'シャドウバイパー', 'map': '風止みの荒地'},
    {'pid': '7546', 'name': 'シャドウバイパーのテール', 'kind': '小怪掉落', 'obtain': 'fld004', 'mappic': '4', 'sfrom': 'シャドウバイパー', 'map': 'オルビド平野'},
    {'pid': '7547', 'name': 'リザードゴーストの澄んだ目玉', 'kind': '小怪掉落', 'obtain': 'fld002', 'mappic': '4', 'sfrom': 'リザードゴースト', 'map': '神の見守る丘'},
    {'pid': '7548', 'name': 'リザードゴーストの尖鋭な背ビレ', 'kind': '小怪掉落', 'obtain': 'fld004', 'mappic': '4', 'sfrom': 'リザードゴースト', 'map': '陽炎の谷'},
    {'pid': '7549', 'name': 'リザードゴーストの鮮やかな鱗', 'kind': '小怪掉落', 'obtain': 'fld004', 'mappic': '4', 'sfrom': 'リザードゴースト', 'map': 'オルビド平野'},
    {'pid': '7550', 'name': 'ロックリザードの尖った爪', 'kind': '小怪掉落', 'obtain': 'fld003', 'mappic': '4', 'sfrom': 'ロックリザード', 'map': 'リッツェ交易街道'},
    {'pid': '7551', 'name': 'ロックリザードの穿牙', 'kind': '小怪掉落', 'obtain': 'fld003', 'mappic': '4', 'sfrom': 'ロックリザード', 'map': 'ガレィリッジ廃道'},
    {'pid': '7552', 'name': 'ロックリザードの大ヒレ', 'kind': '小怪掉落', 'obtain': 'pub0801', 'mappic': '4', 'sfrom': 'ロックリザード'},
    {'pid': '7553', 'name': 'エビキノコの爪', 'kind': '小怪掉落', 'obtain': 'fld003', 'mappic': '4', 'sfrom': 'エビキノコ', 'map': 'リッツェ交易街道'},
    {'pid': '7554', 'name': 'カニクモの爪', 'kind': '小怪掉落', 'obtain': 'fld003', 'mappic': '4', 'sfrom': 'カニクモ', 'map': 'メリソス川流域'},
    {'pid': '7555', 'name': 'オオカニクモの立派な殻', 'kind': '小怪掉落', 'obtain': 'fld004', 'mappic': '4', 'sfrom': 'オオカニクモ', 'map': '風止みの荒地'},
    {'pid': '7556', 'name': 'ナッポの甘い果汁', 'kind': '小怪掉落', 'obtain': 'fld003', 'mappic': '4', 'sfrom': 'ナッポ', 'map': 'メリソス川流域'},
    {'pid': '7557', 'name': 'ナッポの扇葉', 'kind': '小怪掉落', 'obtain': 'fld003', 'mappic': '4', 'sfrom': 'ナッポ', 'map': 'ガレィリッジ廃道'},
    {'pid': '7558', 'name': 'カガチヤンマの羽', 'kind': '小怪掉落', 'obtain': 'fld003', 'mappic': '4', 'sfrom': 'カガチヤンマ', 'map': 'リッツェ交易街道'},
    {'pid': '7559', 'name': 'カガチヤンマの体液', 'kind': '小怪掉落', 'obtain': 'fld004', 'mappic': '4', 'sfrom': 'カガチヤンマ', 'map': '風止みの荒地'},
    {'pid': '7560', 'name': 'オオカガチヤンマの立派な殻', 'kind': '小怪掉落', 'obtain': 'fld004', 'mappic': '4', 'sfrom': 'オオカガチヤンマ', 'map': '帰らずの砂塵'},
    {'pid': '7561', 'name': 'オオカガチヤンマの厚い頭殻', 'kind': '小怪掉落', 'obtain': 'fld004', 'mappic': '4', 'sfrom': 'オオカガチヤンマ', 'map': 'オルビド平野'},
    {'pid': '7562', 'name': '山賊の戦靴', 'kind': '小怪掉落', 'obtain': 'fld001', 'mappic': '4', 'sfrom': '山賊', 'map': 'アンドラ盆地'},
    {'pid': '7563', 'name': '山賊の鋭利な剣', 'kind': '小怪掉落', 'obtain': 'fld004', 'mappic': '4', 'sfrom': '山賊', 'map': 'レインフォール旧街道'},
    {'pid': '7564', 'name': '山賊の射手の手袋', 'kind': '小怪掉落', 'obtain': 'fld001', 'mappic': '4', 'sfrom': '山賊の射手', 'map': '夕凪の段丘'},
    {'pid': '7565', 'name': '山賊の射手のズボン', 'kind': '小怪掉落', 'obtain': 'fld004', 'mappic': '4', 'sfrom': '山賊の射手', 'map': '陽炎の谷'},
    {'pid': '7566', 'name': '山賊の斥候の上着', 'kind': '小怪掉落', 'obtain': 'fld004', 'mappic': '4', 'sfrom': '山賊の斥候', 'map': 'レインフォール旧街道'},
    {'pid': '7567', 'name': '山賊の斥候の剣', 'kind': '小怪掉落', 'obtain': 'fld004', 'mappic': '4', 'sfrom': '山賊の斥候', 'map': '陽炎の谷'},
    {'pid': '7568', 'name': '山賊の斥候の戦靴', 'kind': '小怪掉落', 'obtain': 'pub0201', 'mappic': '4', 'sfrom': '山賊の斥候'},
    {'pid': '7569', 'name': '山賊の術士の重い戦靴', 'kind': '小怪掉落', 'obtain': 'fld004', 'mappic': '4', 'sfrom': '山賊の術士', 'map': '陽炎の谷'},
    {'pid': '7570', 'name': '山賊の護衛の上着', 'kind': '小怪掉落', 'obtain': 'pub0201', 'mappic': '4', 'sfrom': '山賊の護衛'},
    {'pid': '7571', 'name': 'タイラントボアの無傷の牙', 'kind': '小怪掉落', 'obtain': 'pub0803', 'mappic': '4', 'sfrom': 'タイラントボア'},
    {'pid': '7572', 'name': 'ドラウグ・エッジの破片', 'kind': '小怪掉落', 'obtain': 'pub0803', 'mappic': '4', 'sfrom': 'ドラウグ・エッジ'},
    {'pid': '7573', 'name': 'ゴーレムの核', 'kind': '小怪掉落', 'obtain': 'dng007', 'mappic': '4', 'sfrom': 'ゴーレム'},
    {'pid': '7574', 'name': 'バラージアームの機鎧', 'kind': '小怪掉落', 'obtain': 'dng007', 'mappic': '4', 'sfrom': 'バラージアーム'},
    {'pid': '7575', 'name': 'ゾルキシア銃機兵のグローブ', 'kind': '小怪掉落', 'obtain': 'dng007', 'mappic': '4', 'sfrom': 'ゾルキシア銃機兵'},
    {'pid': '7576', 'name': 'ゾルキシア槍兵の鎧', 'kind': '小怪掉落', 'obtain': 'dng007', 'mappic': '4', 'sfrom': 'ゾルキシア槍兵'},
    {'pid': '7577', 'name': '量産型アイアンコフィンの機鎧', 'kind': '小怪掉落', 'obtain': 'dng007', 'mappic': '4', 'sfrom': '量産型アイアンコフィン'},
    {'pid': '7578', 'name': 'ホーリーエレメントの核', 'kind': '小怪掉落', 'obtain': 'dng007', 'mappic': '4', 'sfrom': 'ホーリーエレメント'},
    {'pid': '7579', 'name': '山賊の斥候の軽甲', 'kind': '小怪掉落', 'obtain': 'pub0803', 'mappic': '4', 'sfrom': '山賊の斥候'},
    {'pid': '7580', 'name': '山賊の術士の靴', 'kind': '小怪掉落', 'obtain': 'pub0803', 'mappic': '4', 'sfrom': '山賊の術士'},
    {'pid': '7581', 'name': 'アイスエレメントの結晶', 'kind': '小怪掉落', 'obtain': 'fld005', 'mappic': '4', 'sfrom': 'アイスエレメント', 'map': 'シュタール海岸'},
    {'pid': '7582', 'name': 'ゴブリン・グロウのたてがみ', 'kind': '小怪掉落', 'obtain': 'dng009', 'mappic': '4', 'sfrom': 'ゴブリン・グロウ'},
    {'pid': '7583', 'name': 'ドラウグ・アルマの欠片', 'kind': '小怪掉落', 'obtain': 'pub0803', 'mappic': '4', 'sfrom': 'ドラウグ・アルマ'},
    {'pid': '7584', 'name': 'デザートファングの毛', 'kind': '小怪掉落', 'obtain': 'pub0901', 'mappic': '4', 'sfrom': 'デザートファング'},
    {'pid': '7585', 'name': 'オオカニクモの丸殻', 'kind': '小怪掉落', 'obtain': 'pub0901', 'mappic': '4', 'sfrom': 'オオカニクモ'},
    {'pid': '7586', 'name': 'ペイルポッドの核', 'kind': '小怪掉落', 'obtain': 'pub0901', 'mappic': '4', 'sfrom': 'ペイルポッド'},
    {'pid': '7587', 'name': 'イグニスエレメントの核', 'kind': '小怪掉落', 'obtain': 'pub0901', 'mappic': '4', 'sfrom': 'イグニスエレメント'},
    {'pid': '7588', 'name': 'イージスポッドの部品', 'kind': '小怪掉落', 'obtain': 'pub0901', 'mappic': '4', 'sfrom': 'イージスポッド'},
    {'pid': '7589', 'name': 'リザードゴーストの特大ヒレ', 'kind': '小怪掉落', 'obtain': 'dng004', 'mappic': '4', 'sfrom': 'リザードゴースト'},
    {'pid': '7590', 'name': 'ゴブリンセージの上たてがみ', 'kind': '小怪掉落', 'obtain': 'dng004', 'mappic': '4', 'sfrom': 'ゴブリンセージ'},
    {'pid': '7591', 'name': 'ドラウグ・エッジのかけら', 'kind': '小怪掉落', 'obtain': 'dng004', 'mappic': '4', 'sfrom': 'ドラウグ・エッジ'},
    {'pid': '7592', 'name': 'アイスエレメントの核', 'kind': '小怪掉落', 'obtain': 'dng004', 'mappic': '4', 'sfrom': 'アイスエレメント'},
    {'pid': '7593', 'name': 'ドゴルマンの生爪', 'kind': '小怪掉落', 'obtain': 'dng004', 'mappic': '4', 'sfrom': 'ドゴルマン'},
    {'pid': '7594', 'name': 'ゴブリンファイターの尖った爪', 'kind': '小怪掉落', 'obtain': 'pub0102', 'mappic': '4', 'sfrom': 'ゴブリンファイター'},
    {'pid': '7595', 'name': 'ゴブリンウォーロードの牙', 'kind': '小怪掉落', 'obtain': 'pub0102', 'mappic': '4', 'sfrom': 'ゴブリンウォーロード'},
    {'pid': '7596', 'name': 'フローティングスフィアのコア', 'kind': '小怪掉落', 'obtain': 'pub0102', 'mappic': '4', 'sfrom': 'フローティングスフィア'},
    {'pid': '7597', 'name': 'フローティングアイの部品', 'kind': '小怪掉落', 'obtain': 'pub0102', 'mappic': '4', 'sfrom': 'フローティングアイ'},
    {'pid': '7598', 'name': 'ペイルアイのコア', 'kind': '小怪掉落', 'obtain': 'pub0102', 'mappic': '4', 'sfrom': 'ペイルアイ'},
    {'pid': '7599', 'name': 'ドゴルマンの穿牙', 'kind': '小怪掉落', 'obtain': 'pub0804', 'mappic': '4', 'sfrom': 'ドゴルマン'},
    {'pid': '7600', 'name': 'ヴェノミーンの針', 'kind': '小怪掉落', 'obtain': 'pub0804', 'mappic': '4', 'sfrom': 'ヴェノミーン'},
    {'pid': '7601', 'name': 'カガチヤンマの硬羽', 'kind': '小怪掉落', 'obtain': 'pub0804', 'mappic': '4', 'sfrom': 'カガチヤンマ'},
    {'pid': '7602', 'name': 'ナッポの葉', 'kind': '小怪掉落', 'obtain': 'pub0804', 'mappic': '4', 'sfrom': 'ナッポ'},
    {'pid': '7603', 'name': 'キャニムークスカウトの毛皮', 'kind': '小怪掉落', 'obtain': 'pub0804', 'mappic': '4', 'sfrom': 'キャニムークスカウト'},
    {'pid': '7604', 'name': 'ムークスカウトの重角', 'kind': '小怪掉落', 'obtain': 'dng015', 'mappic': '4', 'sfrom': 'ムークスカウト'},
    {'pid': '7605', 'name': 'カニクモトラッパーのハサミ', 'kind': '小怪掉落', 'obtain': 'dng015', 'mappic': '4', 'sfrom': 'カニクモトラッパー'},
    {'pid': '7606', 'name': 'エビキノコポイズンの生爪', 'kind': '小怪掉落', 'obtain': 'pub0805', 'mappic': '4', 'sfrom': 'エビキノコポイズン'},
    {'pid': '7607', 'name': 'ダークエレメントの結晶', 'kind': '小怪掉落', 'obtain': 'pub0805', 'mappic': '4', 'sfrom': 'ダークエレメント'},
    {'pid': '7608', 'name': 'カニクモフロストの脚', 'kind': '小怪掉落', 'obtain': 'fld005', 'mappic': '4', 'sfrom': 'カニクモフロスト', 'map': 'シュタール海岸'},
    {'pid': '7609', 'name': 'ゴーリィの尖った爪', 'kind': '小怪掉落', 'obtain': 'fld005', 'mappic': '4', 'sfrom': 'ゴーリィ', 'map': '孤影の城下'},
    {'pid': '7610', 'name': 'アースエレメントの不思議な核', 'kind': '小怪掉落', 'obtain': 'fld005', 'mappic': '4', 'sfrom': 'アースエレメント', 'map': '孤影の城下'},
    {'pid': '7611', 'name': 'ダイアーハウルの穿牙', 'kind': '小怪掉落', 'obtain': 'fld005', 'mappic': '4', 'sfrom': 'ダイアーハウル', 'map': 'シュタール海岸'},
    {'pid': '7612', 'name': 'Ｍフォックスの妖牙', 'kind': '小怪掉落', 'obtain': 'fld005', 'mappic': '4', 'sfrom': 'Ｍフォックス', 'map': '孤影の城下'},
    {'pid': '7613', 'name': 'ドラウグ・アルマの部品', 'kind': '小怪掉落', 'obtain': 'fld005', 'mappic': '4', 'sfrom': 'ドラウグ・アルマ', 'map': 'ラウレーベン古戦場'},
    {'pid': '7614', 'name': 'ダークエレメントの核', 'kind': '小怪掉落', 'obtain': 'fld005', 'mappic': '4', 'sfrom': 'ダークエレメント', 'map': 'ラウレーベン古戦場'},
    {'pid': '7615', 'name': 'デザートファングの獰猛牙', 'kind': '小怪掉落', 'obtain': 'pub0902', 'mappic': '4', 'sfrom': 'デザートファング'},
    {'pid': '7616', 'name': 'サンドバイパーの立派な殻', 'kind': '小怪掉落', 'obtain': 'pub0902', 'mappic': '4', 'sfrom': 'サンドバイパー'},
    {'pid': '7617', 'name': 'ランドホークの柔らかな翼', 'kind': '小怪掉落', 'obtain': 'pub0902', 'mappic': '4', 'sfrom': 'ランドホーク'},
    {'pid': '7618', 'name': 'サンドリザードの爪', 'kind': '小怪掉落', 'obtain': 'pub0902', 'mappic': '4', 'sfrom': 'サンドリザード'},
    {'pid': '7619', 'name': 'マスターゴブリンのたてがみ', 'kind': '小怪掉落', 'obtain': 'pub0202', 'mappic': '4', 'sfrom': 'マスターゴブリン'},
    {'pid': '7620', 'name': 'エビキノコポイズンの尾', 'kind': '小怪掉落', 'obtain': 'fld005', 'mappic': '4', 'sfrom': 'エビキノコポイズン', 'map': 'ラウレーベン古戦場'},
    {'pid': '7621', 'name': 'ゴブリンファイターの爪', 'kind': '小怪掉落', 'obtain': 'pub0202', 'mappic': '4', 'sfrom': 'ゴブリンファイター'},
    {'pid': '7622', 'name': 'エルダーゴブリンの上たてがみ', 'kind': '小怪掉落', 'obtain': 'pub0202', 'mappic': '4', 'sfrom': 'エルダーゴブリン'},
    {'pid': '7623', 'name': 'ブラストポッドの部品', 'kind': '小怪掉落', 'obtain': 'pub0206', 'mappic': '4', 'sfrom': 'ブラストポッド'},
    {'pid': '7624', 'name': 'フローティングアイの核', 'kind': '小怪掉落', 'obtain': 'pub0206', 'mappic': '4', 'sfrom': 'フローティングアイ'},
    {'pid': '7625', 'name': 'イージスポッドの精巧な部品', 'kind': '小怪掉落', 'obtain': 'pub0206', 'mappic': '4', 'sfrom': 'イージスポッド'},
    {'pid': '7626', 'name': '量産型アイアンコフィンの装甲', 'kind': '小怪掉落', 'obtain': 'pub0206', 'mappic': '4', 'sfrom': '量産型アイアンコフィン'},
    {'pid': '7627', 'name': 'Ｆゴブリンの歪な生爪', 'kind': '小怪掉落', 'obtain': 'pub0806', 'mappic': '4', 'sfrom': 'Ｆゴブリン'},
    {'pid': '7628', 'name': 'Ｆゴブリンウォーロードの爪', 'kind': '小怪掉落', 'obtain': 'pub0806', 'mappic': '4', 'sfrom': 'Ｆゴブリンウォーロード'},
    {'pid': '7629', 'name': 'Ｆエルダーゴブリンの獰猛牙', 'kind': '小怪掉落', 'obtain': 'pub0806', 'mappic': '4', 'sfrom': 'Ｆエルダーゴブリン'},
    {'pid': '7630', 'name': 'カイザーエルクの尖った爪', 'kind': '小怪掉落', 'obtain': 'pub0806', 'mappic': '4', 'sfrom': 'カイザーエルク'},
    {'pid': '7631', 'name': 'ゴブリン・グロウのたてがみ②', 'kind': '小怪掉落', 'obtain': 'pub0202', 'mappic': '4', 'sfrom': 'ゴブリン・グロウ'},
    {'pid': '7632', 'name': 'ヒートバイパーの頑殻', 'kind': '小怪掉落', 'obtain': 'pub0903', 'mappic': '4', 'sfrom': 'ヒートバイパー'},
    {'pid': '7633', 'name': 'Ｆサンドバイパーのロングテール', 'kind': '小怪掉落', 'obtain': 'pub0903', 'mappic': '4', 'sfrom': 'Ｆサンドバイパー'},
    {'pid': '7634', 'name': 'Ｆリザードゴーストの研がれた牙', 'kind': '小怪掉落', 'obtain': 'pub0903', 'mappic': '4', 'sfrom': 'リザードゴースト'},
    {'pid': '7635', 'name': '山賊の価値ある財宝', 'kind': '小怪掉落', 'obtain': 'pub0903', 'mappic': '4', 'sfrom': '山賊'},
    {'pid': '7636', 'name': 'カニクモアースの尖った爪', 'kind': '小怪掉落', 'obtain': 'pub0103', 'mappic': '4', 'sfrom': 'カニクモアース'},
    {'pid': '7637', 'name': 'キャニムークアーチャーの角', 'kind': '小怪掉落', 'obtain': 'pub0103', 'mappic': '4', 'sfrom': 'キャニムークアーチャー'},
    {'pid': '7638', 'name': 'マスクモスの旋翼', 'kind': '小怪掉落', 'obtain': 'pub0103', 'mappic': '4', 'sfrom': 'マスクモス'},
    {'pid': '7639', 'name': 'キャニムークウォーリアーの毛皮', 'kind': '小怪掉落', 'obtain': 'pub0103', 'mappic': '4', 'sfrom': 'キャニムークウォーリアー'},
    {'pid': '7640', 'name': 'フラワリングペッカーの美羽', 'kind': '小怪掉落', 'obtain': 'fld006', 'mappic': '4', 'sfrom': 'フラワリングペッカー'},
    {'pid': '7641', 'name': 'ギルミーウォーリアーの頸毛', 'kind': '小怪掉落', 'obtain': 'fld006', 'mappic': '4', 'sfrom': 'ギルミーウォーリアー'},
    {'pid': '7642', 'name': 'フレイムスカイフィッシュの美羽', 'kind': '小怪掉落', 'obtain': 'fld006', 'mappic': '4', 'sfrom': 'フレイムスカイフィッシュ'},
    {'pid': '7643', 'name': 'アーススカイフィッシュの堅鱗', 'kind': '小怪掉落', 'obtain': 'fld006', 'mappic': '4', 'sfrom': 'アーススカイフィッシュ'},
    {'pid': '7644', 'name': 'スワンプリザードのキレイな尻尾', 'kind': '小怪掉落', 'obtain': 'fld006', 'mappic': '4', 'sfrom': 'スワンプリザード'},
    {'pid': '7645', 'name': 'イグニスリザードの整った甲鱗', 'kind': '小怪掉落', 'obtain': 'fld006', 'mappic': '4', 'sfrom': 'イグニスリザード'},
    {'pid': '7646', 'name': 'エルダーギルミーの尾部', 'kind': '小怪掉落', 'obtain': 'fld006', 'mappic': '4', 'sfrom': 'エルダーギルミー'},
    {'pid': '7647', 'name': 'マノーの妖牙', 'kind': '小怪掉落', 'obtain': 'fld006', 'mappic': '4', 'sfrom': 'マノー'},
    {'pid': '7648', 'name': 'ライトニングペッカーの穿孔嘴', 'kind': '小怪掉落', 'obtain': 'fld006', 'mappic': '4', 'sfrom': 'ライトニングペッカー'},
    {'pid': '7649', 'name': 'ヒートバイパーの尖った棘', 'kind': '小怪掉落', 'obtain': 'pub0106', 'mappic': '4', 'sfrom': 'ヒートバイパー'},
    {'pid': '7650', 'name': '山賊の護衛の手套', 'kind': '小怪掉落', 'obtain': 'pub0106', 'mappic': '4', 'sfrom': '山賊の護衛'},
    {'pid': '7651', 'name': 'ＰＭムークの鉤爪', 'kind': '小怪掉落', 'obtain': 'pub0505', 'mappic': '4', 'sfrom': 'ＰＭムーク'},
    {'pid': '7652', 'name': 'エビキノコパライズの傘', 'kind': '小怪掉落', 'obtain': 'pub0505', 'mappic': '4', 'sfrom': 'エビキノコパライズ'},
    {'pid': '7653', 'name': '雷鳴のドラウグ・エッジの柄', 'kind': '小怪掉落', 'obtain': 'pub0302', 'mappic': '4', 'sfrom': '雷鳴のドラウグ・エッジ'},
    {'pid': '7654', 'name': 'ヒーリングポッドの破片', 'kind': '小怪掉落', 'obtain': 'pub0302', 'mappic': '4', 'sfrom': 'ヒーリングポッド'},
    {'pid': '7655', 'name': 'ペイルアイのパーツ', 'kind': '小怪掉落', 'obtain': 'pub0302', 'mappic': '4', 'sfrom': 'ペイルアイ'},
    {'pid': '7656', 'name': 'バラージアームの固い装甲', 'kind': '小怪掉落', 'obtain': 'pub0302', 'mappic': '4', 'sfrom': 'バラージアーム'},
    {'pid': '7657', 'name': 'ブラストポッドの外装', 'kind': '小怪掉落', 'obtain': 'pub0302', 'mappic': '4', 'sfrom': 'ブラストポッド'},
    {'pid': '7658', 'name': 'ゴブリンウォーロードの歪な生爪', 'kind': '小怪掉落', 'obtain': 'pub0807', 'mappic': '4', 'sfrom': 'ゴブリンウォーロード'},
    {'pid': '7659', 'name': 'マインドペッカーの雅羽', 'kind': '小怪掉落', 'obtain': 'pub0807', 'mappic': '4', 'sfrom': 'マインドペッカー'},
    {'pid': '7660', 'name': 'ウリボの毛皮', 'kind': '小怪掉落', 'obtain': 'pub0807', 'mappic': '4', 'sfrom': 'ウリボ'},
    {'pid': '7661', 'name': 'タイラントボアの牙', 'kind': '小怪掉落', 'obtain': 'pub0807', 'mappic': '4', 'sfrom': 'タイラントボア'},
    {'pid': '7662', 'name': 'ヒートファットマンの毛皮', 'kind': '小怪掉落', 'obtain': 'pub0108', 'mappic': '4', 'sfrom': 'ヒートファットマン'},
    {'pid': '7663', 'name': 'ムークウォーリアーの大角', 'kind': '小怪掉落', 'obtain': 'pub0108', 'mappic': '4', 'sfrom': 'ムークウォーリアー'},
    {'pid': '7664', 'name': 'エレキファットマンの生爪', 'kind': '小怪掉落', 'obtain': 'pub0108', 'mappic': '4', 'sfrom': 'エレキファットマン'},
    {'pid': '7665', 'name': 'ムークアーチャーの麗たてがみ', 'kind': '小怪掉落', 'obtain': 'pub0108', 'mappic': '4', 'sfrom': 'ムークアーチャー'},
    {'pid': '7666', 'name': 'イージスポッドの機鎧', 'kind': '小怪掉落', 'obtain': 'pub0604', 'mappic': '4', 'sfrom': 'イージスポッド'},
    {'pid': '7667', 'name': 'イグニスエレメントの結晶', 'kind': '小怪掉落', 'obtain': 'pub0604', 'mappic': '4', 'sfrom': 'イグニスエレメント'},
    {'pid': '7668', 'name': 'フレイムスカイフィッシュの大羽', 'kind': '小怪掉落', 'obtain': 'pub0604', 'mappic': '4', 'sfrom': 'フレイムスカイフィッシュ'},
    {'pid': '7669', 'name': 'ギルミーの生爪', 'kind': '小怪掉落', 'obtain': 'pub0604', 'mappic': '4', 'sfrom': 'ギルミー'},
    {'pid': '7670', 'name': '凍血のドラウグ・エッジの刀身', 'kind': '小怪掉落', 'obtain': 'pub0301', 'mappic': '4', 'sfrom': '凍血のドラウグ・エッジ'},
    {'pid': '7671', 'name': 'ペイルポッドの精巧な部品', 'kind': '小怪掉落', 'obtain': 'pub0301', 'mappic': '4', 'sfrom': 'ペイルポッド'},
    {'pid': '7672', 'name': '贖罪のドラウグ・エッジの欠片', 'kind': '小怪掉落', 'obtain': 'pub0301', 'mappic': '4', 'sfrom': '贖罪のドラウグ・エッジ'},
    {'pid': '7673', 'name': 'ヒーリングポッドの固い装甲', 'kind': '小怪掉落', 'obtain': 'pub0301', 'mappic': '4', 'sfrom': 'ヒーリングポッド'},
    {'pid': '7674', 'name': '業火のドラウグ・エッジの美しい柄', 'kind': '小怪掉落', 'obtain': 'pub0301', 'mappic': '4', 'sfrom': '業火のドラウグ・エッジ'},
    {'pid': '7675', 'name': 'バーンハルト狙撃兵の戦闘靴', 'kind': '小怪掉落', 'obtain': 'pub0506', 'mappic': '4', 'sfrom': 'バーンハルト狙撃兵'},
    {'pid': '7676', 'name': 'Ｍムークスカウトの妖牙', 'kind': '小怪掉落', 'obtain': 'pub0506', 'mappic': '4', 'sfrom': 'Ｍムークスカウト'},
    {'pid': '7677', 'name': 'アースエレメントの結晶', 'kind': '小怪掉落', 'obtain': 'pub0506', 'mappic': '4', 'sfrom': 'アースエレメント'},
    {'pid': '7678', 'name': 'バーンハルト兵のコート', 'kind': '小怪掉落', 'obtain': 'pub0506', 'mappic': '4', 'sfrom': 'バーンハルト兵'},
    {'pid': '7679', 'name': 'Ｍムークの大爪', 'kind': '小怪掉落', 'obtain': 'pub0506', 'mappic': '4', 'sfrom': 'Ｍムーク'},
]