// ◆ SC_value
// ┣ pid 序号
// ┣ name 名字
// ┣ obtain 分布范围
// ┣ kind 获取方式
// ┣ mappic 是否有对应的地图图片文件
// ┗ sfrom 材料类型
var SC_value = [
    { pid: '7901', name: 'ベースクレイ', kind: '其他', obtain: '0', mappic:'2', sfrom:'全采集物'},
    { pid: '7902', name: '力の結晶片G1', kind: '其他', obtain: '0', mappic: '2' , sfrom:'植物、矿物'},
    { pid: '7903', name: '持続の結晶片G1', kind: '其他', obtain: '0', mappic: '2' , sfrom:'植物、矿物' },
    { pid: '7904', name: '世話役の結晶片G1', kind: '其他', obtain: '0', mappic: '2' , sfrom:'植物、矿物'},
    { pid: '7905', name: '世話役の結晶片G2', kind: '其他', obtain: '0', mappic: '2' , sfrom:'植物、矿物'},


    { pid: '7006', name: 'トコヨ草', obtain: '0', kind: '植物采集', mappic:'2', sfrom:'植物'},
    { pid: '7007', name: 'グロークンシード', obtain: '0', kind: '植物采集', mappic:'2', sfrom:'植物'},
    { pid: '7008', name: 'あかつき草', obtain: '1', kind: '植物采集', mappic:'1', sfrom:'植物', Point:113},
    { pid: '7009', name: '長毛草', obtain: '1', kind: '植物采集', mappic:'1', sfrom:'植物', Point:119},
    { pid: '7010', name: '星屑草', obtain: '1', kind: '植物采集', mappic:'1', sfrom:'植物', Point:118},
    { pid: '7011', name: '煙霧苔', obtain: '2', kind: '植物采集', mappic:'1', sfrom:'植物', Point:79},
    { pid: '7012', name: 'ストリガの実', obtain: '2', kind: '植物采集', mappic:'1', sfrom:'植物', Point:80},
    { pid: '7013', name: '道草花', obtain: '3', kind: '植物采集', mappic:'1', sfrom:'植物', Point:99},
    { pid: '7014', name: 'メリソスフラワー', obtain: '3', kind: '植物采集', mappic:'1', sfrom:'植物', Point:103},
    { pid: '7015', name: '寂れユリ', obtain: '3', kind: '植物采集', mappic:'1', sfrom:'植物', Point:106},
    { pid: '7016', name: '砂丘斑点虫', obtain: '4', kind: '植物采集', mappic:'1', sfrom:'植物', Point:191},
    { pid: '7017', name: 'レインフォールハーブ', obtain: '4', kind: '植物采集', mappic:'1', sfrom:'植物', Point:194},
    { pid: '7018', name: '砂ミミズ', obtain: '4', kind: '植物采集', mappic:'1', sfrom:'植物', Point:187},
    { pid: '7019', name: '砂蝋枝', obtain: '4', kind: '植物采集', mappic:'1', sfrom:'植物', Point:190},
    { pid: '7020', name: 'ミラービーンズ', obtain: '4', kind: '植物采集', mappic:'1', sfrom:'植物', Point:196},
    { pid: '7021', name: 'リュウノツメモドキ', obtain: '9', kind: '植物采集', mappic:'1', sfrom:'植物', Point:19},
    { pid: '7022', name: '燃える妖花', obtain: '9', kind: '植物采集', mappic:'1', sfrom:'植物', Point:21},
    { pid: '7023', name: 'フィエルの若木', obtain: '6', kind: '植物采集', mappic:'1', sfrom:'植物', Point:23},
    { pid: '7024', name: '静寂草', obtain: '7', kind: '植物采集', mappic:'1', sfrom:'植物', Point:19},
    { pid: '7025', name: 'オイルシェールグラス', obtain: '11', kind: '植物采集', mappic:'1', sfrom:'植物', Point:12},
    { pid: '7026', name: 'ドーンマッシュルーム', obtain: '10', kind: '植物采集', mappic:'1', sfrom:'植物', Point:18},
    { pid: '7027', name: 'メンヨウ草', obtain: '18', kind: '植物采集', mappic:'1', sfrom:'植物', Point:25},
    { pid: '7028', name: '半島カナムグラ', obtain: '5', kind: '植物采集', mappic:'1', sfrom:'植物', Point:84},
    { pid: '7029', name: '氷点花', obtain: '5', kind: '植物采集', mappic:'1', sfrom:'植物', Point:88},
    { pid: '7030', name: 'カムノキの新芽', obtain: '5', kind: '植物采集', mappic:'1', sfrom:'植物', Point:89},
    { pid: '7031', name: 'ドラファーフ草', obtain: '21', kind: '植物采集', mappic:'1', sfrom:'植物', Point:14},
    { pid: '7032', name: '山麓ナデシコ', obtain: '13', kind: '植物采集', mappic:'1', sfrom:'植物', Point:11},
    { pid: '7033', name: 'クロネッタの果実', obtain: '19', kind: '植物采集', mappic:'1', sfrom:'植物', Point:17},
    { pid: '7034', name: 'トンネルヨモギ', obtain: '14', kind: '植物采集', mappic:'1', sfrom:'植物', Point:11},
    { pid: '7035', name: 'スナリプル草', obtain: '22', kind: '植物采集', mappic:'1', sfrom:'植物', Point:24},
    { pid: '7036', name: '高嶺バッタ', obtain: '23', kind: '植物采集', mappic:'1', sfrom:'植物', Point:9},
    

    { pid: '7207', name: '水晶の原石', kind: '矿物采集', obtain: '0', mappic: '2', sfrom:'矿物'},
    { pid: '7208', name: '環状石', kind: '矿物采集', obtain: '0', mappic: '2', sfrom:'矿物'},
    { pid: '7209', name: '平原ヒスイ', kind: '矿物采集', obtain: '1', mappic: '1', sfrom:'矿物', Point:112},
    { pid: '7210', name: 'アステリウム鉱石', kind: '矿物采集', obtain: '1', mappic: '1', sfrom:'矿物', Point:114},
    { pid: '7211', name: 'ジラ輝石', kind: '矿物采集', obtain: '1', mappic: '1', sfrom:'矿物', Point:116},
    { pid: '7212', name: '隕鉄の欠片', kind: '矿物采集', obtain: '1', mappic: '1', sfrom:'矿物', Point:117},
    { pid: '7213', name: 'バハ鉱石', kind: '矿物采集', obtain: '2', mappic: '1', sfrom:'矿物', Point:81},
    { pid: '7214', name: '静夜鉱', kind: '矿物采集', obtain: '2', mappic: '1', sfrom:'矿物', Point:82},
    { pid: '7215', name: '湧水石', kind: '矿物采集', obtain: '2', mappic: '1', sfrom:'矿物', Point:83},
    { pid: '7216', name: 'モンテノールストーン', kind: '矿物采集', obtain: '3', mappic: '1', sfrom:'矿物', Point:100},
    { pid: '7217', name: 'メリソス石灰石', kind: '矿物采集', obtain: '3', mappic: '1', sfrom:'矿物', Point:102},
    { pid: '7218', name: 'エバーグリーン雲母砂', kind: '矿物采集', obtain: '4', mappic: '1', sfrom:'矿物', Point:192},
    { pid: '7219', name: '雨唄いの化石', kind: '矿物采集', obtain: '4', mappic: '1', sfrom:'矿物', Point:193},
    { pid: '7220', name: '谷底白砂', kind: '矿物采集', obtain: '4', mappic: '1', sfrom:'矿物', Point:188},
    { pid: '7221', name: '風の這痕', kind: '矿物采集', obtain: '4', mappic: '1', sfrom:'矿物', Point:189},
    { pid: '7222', name: '砂丘生痕', kind: '矿物采集', obtain: '4', mappic: '1', sfrom:'矿物', Point:195},
    { pid: '7223', name: '哭竜鉱', kind: '矿物采集', obtain: '9', mappic: '1', sfrom:'矿物', Point:18},
    { pid: '7224', name: '翼竜の化石', kind: '矿物采集', obtain: '9', mappic: '1', sfrom:'矿物', Point:20},
    { pid: '7225', name: '風故物', kind: '矿物采集', obtain: '15', mappic: '1', sfrom:'矿物', Point:22},
    { pid: '7226', name: 'ボルオム鉛', kind: '矿物采集', obtain: '12', mappic: '1', sfrom:'矿物', Point:9},
    { pid: '7227', name: '落星孔雀石', kind: '矿物采集', obtain: '6', mappic: '1', sfrom:'矿物', Point:22},
    { pid: '7228', name: '硬化プレート', kind: '矿物采集', obtain: '16', mappic: '1', sfrom:'矿物', Point:17},
    { pid: '7229', name: '謎の金属', kind: '矿物采集', obtain: '8', mappic: '1', sfrom:'矿物', Point:20},
    { pid: '7230', name: '盛時の礫塊', kind: '矿物采集', obtain: '7', mappic: '1', sfrom:'矿物', Point:20},
    { pid: '7231', name: '風止みの遺物', kind: '矿物采集', obtain: '20', mappic: '1', sfrom:'矿物', Point:23},
    { pid: '7232', name: '浮かぶ車輪', kind: '矿物采集', obtain: '17', mappic: '1', sfrom:'矿物', Point:19},
    { pid: '7233', name: '星状輝石', kind: '矿物采集', obtain: '11', mappic: '1', sfrom:'矿物', Point:13},
    { pid: '7234', name: 'アミメバチ', kind: '矿物采集', obtain: '10', mappic: '1', sfrom:'矿物', Point:19},
    { pid: '7235', name: '曇天結晶', kind: '矿物采集', obtain: '18', mappic: '1', sfrom:'矿物', Point:26},
    { pid: '7236', name: 'ミダイエ鉱', kind: '矿物采集', obtain: '5', mappic: '1', sfrom:'矿物', Point:85},
    { pid: '7237', name: 'アイアンヘルムの破片', kind: '矿物采集', obtain: '5', mappic: '1', sfrom:'矿物', Point:87},
    { pid: '7238', name: 'オルドナイト', kind: '矿物采集', obtain: '5', mappic: '1', sfrom:'矿物', Point:90},
    { pid: '7239', name: 'アランダル歯車', kind: '矿物采集', obtain: '21', mappic: '1', sfrom:'矿物', Point:15},
    { pid: '7240', name: 'インボルナイト', kind: '矿物采集', obtain: '13', mappic: '1', sfrom:'矿物', Point:12},
    { pid: '7241', name: 'スピンドルパーツ', kind: '矿物采集', obtain: '14', mappic: '1', sfrom:'矿物', Point:12},
    { pid: '7242', name: 'モスメタル', kind: '矿物采集', obtain: '19', mappic: '1', sfrom:'矿物', Point:18},
    { pid: '7243', name: 'サイコロ晶体', kind: '矿物采集', obtain: '22', mappic: '1', sfrom:'矿物', Point:25},
    { pid: '7244', name: 'ジャイロディスク', kind: '矿物采集', obtain: '23', mappic: '1', sfrom:'矿物', Point:10},
      

    { pid: '7401', name: '割れた貝殻', kind: '水栖采集', obtain: '0', mappic: '2', sfrom:'水栖'},
    { pid: '7402', name: 'さざなみ石', kind: '水栖采集', obtain: '0', mappic: '2', sfrom:'水栖'},
    { pid: '7403', name: '旅藻草', kind: '水栖采集', obtain: '1', mappic: '1', sfrom:'水栖', Point:115},
    { pid: '7404', name: 'フィエル蓮葉', kind: '水栖采集', obtain: '2', mappic: '1', sfrom:'水栖', Point:84},
    { pid: '7405', name: 'リッツェホーンウッド', kind: '水栖采集', obtain: '3', mappic: '1', sfrom:'水栖', Point:101},
    { pid: '7406', name: '急流藻草', kind: '水栖采集', obtain: '3', mappic: '1', sfrom:'水栖', Point:104},
    { pid: '7407', name: 'モンテノール池苔', kind: '水栖采集', obtain: '3', mappic: '1', sfrom:'水栖', Point:105},
    { pid: '7408', name: '海蛇草', kind: '水栖采集', obtain: '5', mappic: '1', sfrom:'水栖', Point:86},
    { pid: '7409', name: 'ランツェウッド', kind: '水栖采集', obtain: '5', mappic: '1', sfrom:'水栖', Point:91},

    
    { pid: '7501', name: '動的エングラムの欠片', kind: '小怪掉落', obtain: '0', mappic: '0' , sfrom:'任意小怪'},
    { pid: '7502', name: '動的エングラム結晶片', kind: '小怪掉落', obtain: '0', mappic: '0' , sfrom:'任意小怪'},
    { pid: '7503', name: '火精の結晶片G1', kind: '小怪掉落', obtain: '0', mappic: '0' , sfrom:'对应属性小怪'},
    { pid: '7504', name: '氷精の結晶片G1', kind: '小怪掉落', obtain: '0', mappic: '0' , sfrom:'对应属性小怪'},
    { pid: '7505', name: '雷精の結晶片G1', kind: '小怪掉落', obtain: '0', mappic: '0' , sfrom:'对应属性小怪'},
    { pid: '7506', name: '土精の結晶片G1', kind: '小怪掉落', obtain: '0', mappic: '0' , sfrom:'对应属性小怪'},
    { pid: '7507', name: 'グレートファングの研がれた牙', kind: '小怪掉落', obtain: '4', mappic: '4' , sfrom:'グレートファング', map:'レインフォール旧街道'},
    { pid: '7508', name: 'タイラントボア・グロウの上質な毛皮', kind: '小怪掉落', obtain: '1', mappic: '4' , sfrom:'タイラントボア・グロウ', map:'夕凪の段丘'},
    { pid: '7509', name: 'ランブルボアの爪', kind: '小怪掉落', obtain: '1', mappic: '4' , sfrom:'ランブルボア', map:'アンドラ盆地'},
    { pid: '7510', name: 'デザートファングの高品質な毛皮', kind: '小怪掉落', obtain: '4', mappic: '4' , sfrom:'デザートファング', map:'レインフォール旧街道'},
    { pid: '7511', name: 'デザートファングの尖った爪', kind: '小怪掉落', obtain: '4', mappic: '4' , sfrom:'デザートファング', map:'風止みの荒地'},
    { pid: '7512', name: 'ウリボの尾', kind: '小怪掉落', obtain: '1', mappic: '4' , sfrom:'ウリボ', map:"海鳴りの草原"},
    { pid: '7513', name: 'ホーンゴートの角', kind: '小怪掉落', obtain: '2', mappic: '4', sfrom: 'ホーンゴート', map:"神の見守る丘"},
    { pid: '7514', name: 'ホーンゴートの毛皮', kind: '小怪掉落', obtain: '2', mappic: '4', sfrom: 'ホーンゴート', map:"フィエル嶺水池"},
    { pid: '7515', name: 'カイザーエルクの毛皮', kind: '小怪掉落', obtain: '2', mappic: '4', sfrom: 'カイザーエルク', map:"神の見守る丘"},
    { pid: '7516', name: 'ランドフォックスの尻尾', kind: '小怪掉落', obtain: '1', mappic: '4', sfrom: 'ランドフォックス', map:"ミンスター丘陵"},
    { pid: '7517', name: 'ハイランドフォックスの爪', kind: '小怪掉落', obtain: '2', mappic: '4', sfrom: 'ハイランドフォックス', map:"鎮まりの山麓"},
    { pid: '7518', name: 'ハイランドフォックスの牙', kind: '小怪掉落', obtain: '2', mappic: '4', sfrom: 'ハイランドフォックス', map:"神の見守る丘"},
    { pid: '7519', name: 'ランドホークの穿孔嘴', kind: '小怪掉落', obtain: '4', mappic: '4', sfrom: 'ランドホーク', map:"帰らずの砂塵"},
    { pid: '7520', name: 'ランドホークの鉤爪', kind: '小怪掉落', obtain: '4', mappic: '4', sfrom: 'ランドホーク', map:"オルビド平野"},
    { pid: '7521', name: 'ゴブリンの棍棒', kind: '小怪掉落', obtain: '1', mappic: '4', sfrom: 'ゴブリン', map:"アンドラ盆地"},
    { pid: '7522', name: 'ゴブリンのたてがみ', kind: '小怪掉落', obtain: '2', mappic: '4', sfrom: 'ゴブリン', map:"鎮まりの山麓"},
    { pid: '7523', name: 'ゴブリンの尻尾', kind: '小怪掉落', obtain: '2', mappic: '4', sfrom: 'ゴブリン', map:"フィエル嶺水池"},
    { pid: '7524', name: 'ゴブリンのキバ', kind: '小怪掉落', obtain: '9', mappic: '4', sfrom: 'ゴブリン' },
    { pid: '7525', name: 'エルダーゴブリンの杖', kind: '小怪掉落', obtain: '1', mappic: '4', sfrom: 'エルダーゴブリン', map:"夕凪の段丘"},
    { pid: '7526', name: 'エルダーゴブリンの首飾り', kind: '小怪掉落', obtain: '2', mappic: '4', sfrom: 'エルダーゴブリン', map:"鎮まりの山麓"},
    { pid: '7527', name: 'ゴブリンウォーリアーのたてがみ', kind: '小怪掉落', obtain: '2', mappic: '4', sfrom: 'ゴブリンウォーリアー', map:"鎮まりの山麓"},
    { pid: '7528', name: 'ゴブリンウォーリアーの尖った爪', kind: '小怪掉落', obtain: '2', mappic: '4', sfrom: 'ゴブリンウォーリアー', map:"フィエル嶺水池"},
    { pid: '7529', name: 'ゴブリンセージの杖', kind: '小怪掉落', obtain: '6', mappic: '4', sfrom: 'ゴブリンセージ' },
    { pid: '7530', name: 'ムークの頸毛', kind: '小怪掉落', obtain: '3', mappic: '4', sfrom: 'ムーク', map:"リッツェ交易街道"},
    { pid: '7531', name: 'ムークの鉤爪', kind: '小怪掉落', obtain: '3', mappic: '4', sfrom: 'ムーク', map:"メリソス川流域"},
    { pid: '7532', name: 'ムークの爪', kind: '小怪掉落', obtain: '15', mappic: '4', sfrom: 'ムーク' },
    { pid: '7533', name: 'ムークアーチャーのキバ', kind: '小怪掉落', obtain: '3', mappic: '4', sfrom: 'ムークアーチャー', map:"メリソス川流域"},
    { pid: '7534', name: 'オーガの重角', kind: '小怪掉落', obtain: '1', mappic: '4', sfrom: 'オーガ', map:"夕凪の段丘"},
    { pid: '7535', name: 'ドゴルマンの体毛', kind: '小怪掉落', obtain: '4', mappic: '4', sfrom: 'ドゴルマン', map:"帰らずの砂塵"},
    { pid: '7536', name: 'ミーンの羽', kind: '小怪掉落', obtain: '3', mappic: '4', sfrom: 'ミーン', map:"リッツェ交易街道"},
    { pid: '7537', name: 'ミーンの針', kind: '小怪掉落', obtain: '3', mappic: '4', sfrom: 'ミーン', map:"ガレィリッジ廃道"},
    { pid: '7538', name: 'ミーンの丸殻', kind: '小怪掉落', obtain: '15', mappic: '4', sfrom: 'ミーン' },
    { pid: '7539', name: 'サンドバイパーの甲殻', kind: '小怪掉落', obtain: '4', mappic: '4', sfrom: 'サンドバイパー', map:"レインフォール旧街道"},
    { pid: '7540', name: 'サンドバイパーの殻', kind: '小怪掉落', obtain: '4', mappic: '4', sfrom: 'サンドバイパー', map:"陽炎の谷"},
    { pid: '7541', name: 'サンドバイパーの棘', kind: '小怪掉落', obtain: '4', mappic: '4', sfrom: 'サンドバイパー', map:"風止みの荒地"},
    { pid: '7542', name: 'サンドバイパーのテール', kind: '小怪掉落', obtain: '4', mappic: '4', sfrom: 'サンドバイパー', map:"オルビド平野"},
    { pid: '7543', name: 'シャドウバイパーの立派な殻', kind: '小怪掉落', obtain: '4', mappic: '4', sfrom: 'シャドウバイパー', map:"レインフォール旧街道"},
    { pid: '7544', name: 'シャドウバイパーのロングテール', kind: '小怪掉落', obtain: '4', mappic: '4', sfrom: 'シャドウバイパー', map:"陽炎の谷"},
    { pid: '7545', name: 'シャドウバイパーの厚手の外皮', kind: '小怪掉落', obtain: '4', mappic: '4', sfrom: 'シャドウバイパー', map:"風止みの荒地"},
    { pid: '7546', name: 'シャドウバイパーのテール', kind: '小怪掉落', obtain: '4', mappic: '4', sfrom: 'シャドウバイパー', map:"オルビド平野"},
    { pid: '7547', name: 'リザードゴーストの澄んだ目玉', kind: '小怪掉落', obtain: '2', mappic: '4', sfrom: 'リザードゴースト', map:"神の見守る丘"},
    { pid: '7548', name: 'リザードゴーストの尖鋭な背ビレ', kind: '小怪掉落', obtain: '4', mappic: '4', sfrom: 'リザードゴースト', map:"陽炎の谷"},
    { pid: '7549', name: 'リザードゴーストの鮮やかな鱗', kind: '小怪掉落', obtain: '4', mappic: '4', sfrom: 'リザードゴースト', map:"オルビド平野"},
    { pid: '7550', name: 'ロックリザードの尖った爪', kind: '小怪掉落', obtain: '3', mappic: '4', sfrom: 'ロックリザード', map:"リッツェ交易街道"},
    { pid: '7551', name: 'ロックリザードの穿牙', kind: '小怪掉落', obtain: '3', mappic: '4', sfrom: 'ロックリザード', map:"ガレィリッジ廃道"},
    { pid: '7552', name: 'ロックリザードの大ヒレ', kind: '小怪掉落', obtain: '15', mappic: '4', sfrom: 'ロックリザード' },
    { pid: '7553', name: 'エビキノコの爪', kind: '小怪掉落', obtain: '3', mappic: '4', sfrom: 'エビキノコ', map:"リッツェ交易街道"},
    { pid: '7554', name: 'カニクモの爪', kind: '小怪掉落', obtain: '3', mappic: '4', sfrom: 'カニクモ', map:"メリソス川流域"},
    { pid: '7555', name: 'オオカニクモの立派な殻', kind: '小怪掉落', obtain: '4', mappic: '4', sfrom: 'オオカニクモ', map:"風止みの荒地"},
    { pid: '7556', name: 'ナッポの甘い果汁', kind: '小怪掉落', obtain: '3', mappic: '4', sfrom: 'ナッポ', map:"メリソス川流域"},
    { pid: '7557', name: 'ナッポの扇葉', kind: '小怪掉落', obtain: '3', mappic: '4', sfrom: 'ナッポ', map:"ガレィリッジ廃道"},
    { pid: '7558', name: 'カガチヤンマの羽', kind: '小怪掉落', obtain: '3', mappic: '4', sfrom: 'カガチヤンマ', map:"リッツェ交易街道"},
    { pid: '7559', name: 'カガチヤンマの体液', kind: '小怪掉落', obtain: '4', mappic: '4', sfrom: 'カガチヤンマ', map:"風止みの荒地"},
    { pid: '7560', name: 'オオカガチヤンマの立派な殻', kind: '小怪掉落', obtain: '4', mappic: '4', sfrom: 'オオカガチヤンマ', map:"帰らずの砂塵"},
    { pid: '7561', name: 'オオカガチヤンマの厚い頭殻', kind: '小怪掉落', obtain: '4', mappic: '4', sfrom: 'オオカガチヤンマ', map:"オルビド平野"},
    { pid: '7562', name: '山賊の戦靴', kind: '小怪掉落', obtain: '1', mappic: '4', sfrom: '山賊', map:"アンドラ盆地"},
    { pid: '7563', name: '山賊の鋭利な剣', kind: '小怪掉落', obtain: '4', mappic: '4', sfrom: '山賊', map:"レインフォール旧街道"},
    { pid: '7564', name: '山賊の射手の手袋', kind: '小怪掉落', obtain: '1', mappic: '4', sfrom: '山賊の射手', map:"夕凪の段丘"},
    { pid: '7565', name: '山賊の射手のズボン', kind: '小怪掉落', obtain: '4', mappic: '4', sfrom: '山賊の射手', map:"陽炎の谷"},
    { pid: '7566', name: '山賊の斥候の上着', kind: '小怪掉落', obtain: '4', mappic: '4', sfrom: '山賊の斥候', map:"レインフォール旧街道"},
    { pid: '7567', name: '山賊の斥候の剣', kind: '小怪掉落', obtain: '4', mappic: '4', sfrom: '山賊の斥候', map:"陽炎の谷"},
    { pid: '7568', name: '山賊の斥候の戦靴', kind: '小怪掉落', obtain: '12', mappic: '4', sfrom: '山賊の斥候' },
    { pid: '7569', name: '山賊の術士の重い戦靴', kind: '小怪掉落', obtain: '4', mappic: '4', sfrom: '山賊の術士', map:"陽炎の谷"},
    { pid: '7570', name: '山賊の護衛の上着', kind: '小怪掉落', obtain: '12', mappic: '4', sfrom: '山賊の護衛' },
    { pid: '7571', name: 'タイラントボアの無傷の牙', kind: '小怪掉落', obtain: '16', mappic: '4', sfrom: 'タイラントボア' },
    { pid: '7572', name: 'ドラウグ・エッジの破片', kind: '小怪掉落', obtain: '16', mappic: '4', sfrom: 'ドラウグ・エッジ' },
    { pid: '7573', name: 'ゴーレムの核', kind: '小怪掉落', obtain: '8', mappic: '4', sfrom: 'ゴーレム' },
    { pid: '7574', name: 'バラージアームの機鎧', kind: '小怪掉落', obtain: '8', mappic: '4', sfrom: 'バラージアーム' },
    { pid: '7575', name: 'ゾルキシア銃機兵のグローブ', kind: '小怪掉落', obtain: '8', mappic: '4', sfrom: 'ゾルキシア銃機兵' },
    { pid: '7576', name: 'ゾルキシア槍兵の鎧', kind: '小怪掉落', obtain: '8', mappic: '4', sfrom: 'ゾルキシア槍兵' },
    { pid: '7577', name: '量産型アイアンコフィンの機鎧', kind: '小怪掉落', obtain: '8', mappic: '4', sfrom: '量産型アイアンコフィン' },
    { pid: '7578', name: 'ホーリーエレメントの核', kind: '小怪掉落', obtain: '8', mappic: '4', sfrom: 'ホーリーエレメント' },
    { pid: '7579', name: '山賊の斥候の軽甲', kind: '小怪掉落', obtain: '16', mappic: '4', sfrom: '山賊の斥候' },
    { pid: '7580', name: '山賊の術士の靴', kind: '小怪掉落', obtain: '16', mappic: '4', sfrom: '山賊の術士' },
    { pid: '7581', name: 'アイスエレメントの結晶', kind: '小怪掉落', obtain: '5', mappic: '4', sfrom: 'アイスエレメント', map:"シュタール海岸"},
    { pid: '7582', name: 'ゴブリン・グロウのたてがみ', kind: '小怪掉落', obtain: '9', mappic: '4', sfrom: 'ゴブリン・グロウ' },
    { pid: '7583', name: 'ドラウグ・アルマの欠片', kind: '小怪掉落', obtain: '16', mappic: '4', sfrom: 'ドラウグ・アルマ' },
    { pid: '7584', name: 'デザートファングの毛', kind: '小怪掉落', obtain: '20', mappic: '4', sfrom: 'デザートファング' },
    { pid: '7585', name: 'オオカニクモの丸殻', kind: '小怪掉落', obtain: '20', mappic: '4', sfrom: 'オオカニクモ' },
    { pid: '7586', name: 'ペイルポッドの核', kind: '小怪掉落', obtain: '20', mappic: '4', sfrom: 'ペイルポッド' },
    { pid: '7587', name: 'イグニスエレメントの核', kind: '小怪掉落', obtain: '20', mappic: '4', sfrom: 'イグニスエレメント' },
    { pid: '7588', name: 'イージスポッドの部品', kind: '小怪掉落', obtain: '20', mappic: '4', sfrom: 'イージスポッド' },
    { pid: '7589', name: 'リザードゴーストの特大ヒレ', kind: '小怪掉落', obtain: '7', mappic: '4', sfrom: 'リザードゴースト' },
    { pid: '7590', name: 'ゴブリンセージの上たてがみ', kind: '小怪掉落', obtain: '7', mappic: '4', sfrom: 'ゴブリンセージ' },
    { pid: '7591', name: 'ドラウグ・エッジのかけら', kind: '小怪掉落', obtain: '7', mappic: '4', sfrom: 'ドラウグ・エッジ' },
    { pid: '7592', name: 'アイスエレメントの核', kind: '小怪掉落', obtain: '7', mappic: '4', sfrom: 'アイスエレメント' },
    { pid: '7593', name: 'ドゴルマンの生爪', kind: '小怪掉落', obtain: '7', mappic: '4', sfrom: 'ドゴルマン' },
    { pid: '7594', name: 'ゴブリンファイターの尖った爪', kind: '小怪掉落', obtain: '11', mappic: '4', sfrom: 'ゴブリンファイター' },
    { pid: '7595', name: 'ゴブリンウォーロードの牙', kind: '小怪掉落', obtain: '11', mappic: '4', sfrom: 'ゴブリンウォーロード' },
    { pid: '7596', name: 'フローティングスフィアのコア', kind: '小怪掉落', obtain: '11', mappic: '4', sfrom: 'フローティングスフィア' },
    { pid: '7597', name: 'フローティングアイの部品', kind: '小怪掉落', obtain: '11', mappic: '4', sfrom: 'フローティングアイ' },
    { pid: '7598', name: 'ペイルアイのコア', kind: '小怪掉落', obtain: '11', mappic: '4', sfrom: 'ペイルアイ' },
    { pid: '7599', name: 'ドゴルマンの穿牙', kind: '小怪掉落', obtain: '17', mappic: '4', sfrom: 'ドゴルマン' },
    { pid: '7600', name: 'ヴェノミーンの針', kind: '小怪掉落', obtain: '17', mappic: '4', sfrom: 'ヴェノミーン' },
    { pid: '7601', name: 'カガチヤンマの硬羽', kind: '小怪掉落', obtain: '17', mappic: '4', sfrom: 'カガチヤンマ' },
    { pid: '7602', name: 'ナッポの葉', kind: '小怪掉落', obtain: '17', mappic: '4', sfrom: 'ナッポ' },
    { pid: '7603', name: 'キャニムークスカウトの毛皮', kind: '小怪掉落', obtain: '17', mappic: '4', sfrom: 'キャニムークスカウト' },
    { pid: '7604', name: 'ムークスカウトの重角', kind: '小怪掉落', obtain: '10', mappic: '4', sfrom: 'ムークスカウト' },
    { pid: '7605', name: 'カニクモトラッパーのハサミ', kind: '小怪掉落', obtain: '10', mappic: '4', sfrom: 'カニクモトラッパー' },
    { pid: '7606', name: 'エビキノコポイズンの生爪', kind: '小怪掉落', obtain: '18', mappic: '4', sfrom: 'エビキノコポイズン' },
    { pid: '7607', name: 'ダークエレメントの結晶', kind: '小怪掉落', obtain: '18', mappic: '4', sfrom: 'ダークエレメント' },
    { pid: '7608', name: 'カニクモフロストの脚', kind: '小怪掉落', obtain: '5', mappic: '4', sfrom: 'カニクモフロスト', map:"シュタール海岸"},
    { pid: '7609', name: 'ゴーリィの尖った爪', kind: '小怪掉落', obtain: '5', mappic: '4', sfrom: 'ゴーリィ', map:"孤影の城下"},
    { pid: '7610', name: 'アースエレメントの不思議な核', kind: '小怪掉落', obtain: '5', mappic: '4', sfrom: 'アースエレメント', map:"孤影の城下"},
    { pid: '7611', name: 'ダイアーハウルの穿牙', kind: '小怪掉落', obtain: '5', mappic: '4', sfrom: 'ダイアーハウル', map:"シュタール海岸"},
    { pid: '7612', name: 'Ｍフォックスの妖牙', kind: '小怪掉落', obtain: '5', mappic: '4', sfrom: 'Ｍフォックス', map:"孤影の城下"},
    { pid: '7613', name: 'ドラウグ・アルマの部品', kind: '小怪掉落', obtain: '5', mappic: '4', sfrom: 'ドラウグ・アルマ', map:"ラウレーベン古戦場"},
    { pid: '7614', name: 'ダークエレメントの核', kind: '小怪掉落', obtain: '5', mappic: '4', sfrom: 'ダークエレメント', map:"ラウレーベン古戦場"},
    { pid: '7615', name: 'デザートファングの獰猛牙', kind: '小怪掉落', obtain: '21', mappic: '4', sfrom: 'デザートファング' },
    { pid: '7616', name: 'サンドバイパーの立派な殻', kind: '小怪掉落', obtain: '21', mappic: '4', sfrom: 'サンドバイパー' },
    { pid: '7617', name: 'ランドホークの柔らかな翼', kind: '小怪掉落', obtain: '21', mappic: '4', sfrom: 'ランドホーク' },
    { pid: '7618', name: 'サンドリザードの爪', kind: '小怪掉落', obtain: '21', mappic: '4', sfrom: 'サンドリザード' },
    { pid: '7619', name: 'マスターゴブリンのたてがみ', kind: '小怪掉落', obtain: '13', mappic: '4', sfrom: 'マスターゴブリン' },
    { pid: '7620', name: 'エビキノコポイズンの尾', kind: '小怪掉落', obtain: '5', mappic: '4', sfrom: 'エビキノコポイズン', map:"ラウレーベン古戦場"},
    { pid: '7621', name: 'ゴブリンファイターの爪', kind: '小怪掉落', obtain: '13', mappic: '4', sfrom: 'ゴブリンファイター' },
    { pid: '7622', name: 'エルダーゴブリンの上たてがみ', kind: '小怪掉落', obtain: '13', mappic: '4', sfrom: 'エルダーゴブリン' },
    { pid: '7623', name: 'ブラストポッドの部品', kind: '小怪掉落', obtain: '14', mappic: '4', sfrom: 'ブラストポッド' },
    { pid: '7624', name: 'フローティングアイの核', kind: '小怪掉落', obtain: '14', mappic: '4', sfrom: 'フローティングアイ' },
    { pid: '7625', name: 'イージスポッドの精巧な部品', kind: '小怪掉落', obtain: '14', mappic: '4', sfrom: 'イージスポッド' },
    { pid: '7626', name: '量産型アイアンコフィンの装甲', kind: '小怪掉落', obtain: '14', mappic: '4', sfrom: '量産型アイアンコフィン' },
    { pid: '7627', name: 'Ｆゴブリンの歪な生爪', kind: '小怪掉落', obtain: '19', mappic: '4', sfrom: 'Ｆゴブリン' },
    { pid: '7628', name: 'Ｆゴブリンウォーロードの爪', kind: '小怪掉落', obtain: '19', mappic: '4', sfrom: 'Ｆゴブリンウォーロード' },
    { pid: '7629', name: 'Ｆエルダーゴブリンの獰猛牙', kind: '小怪掉落', obtain: '19', mappic: '4', sfrom: 'Ｆエルダーゴブリン' },
    { pid: '7630', name: 'カイザーエルクの尖った爪', kind: '小怪掉落', obtain: '19', mappic: '4', sfrom: 'カイザーエルク' },
    { pid: '7631', name: 'ゴブリン・グロウのたてがみ②', kind: '小怪掉落', obtain: '13', mappic: '4', sfrom: 'ゴブリン・グロウ' },
    { pid: '7632', name: 'ヒートバイパーの頑殻', kind: '小怪掉落', obtain: '22', mappic: '4', sfrom: 'ヒートバイパー' },
    { pid: '7633', name: 'Ｆサンドバイパーのロングテール', kind: '小怪掉落', obtain: '22', mappic: '4', sfrom: 'Ｆサンドバイパー' },
    { pid: '7634', name: 'Ｆリザードゴーストの研がれた牙', kind: '小怪掉落', obtain: '22', mappic: '4', sfrom: 'リザードゴースト' },
    { pid: '7635', name: '山賊の価値ある財宝', kind: '小怪掉落', obtain: '22', mappic: '4', sfrom: '山賊' },
    { pid: '7636', name: 'カニクモアースの尖った爪', kind: '小怪掉落', obtain: '23', mappic: '4', sfrom: 'カニクモアース' },
    { pid: '7637', name: 'キャニムークアーチャーの角', kind: '小怪掉落', obtain: '23', mappic: '4', sfrom: 'キャニムークアーチャー' },
    { pid: '7638', name: 'マスクモスの旋翼', kind: '小怪掉落', obtain: '23', mappic: '4', sfrom: 'マスクモス' },
    { pid: '7639', name: 'キャニムークウォーリアーの毛皮', kind: '小怪掉落', obtain: '23', mappic: '4', sfrom: 'キャニムークウォーリアー' },
]