////////////////////////////////////////
//   最近实装单位：newThings 新职业1 新武器2 新幻想e3 新幻想b4 新敌人5
//   情报：willThings   标题(words)     图     url链接(urlOut)    文字（justword）
//   当前活动：nowActivity 卡池1 活动主题图2
var G_value = [
    { kind:'newThings', kindSecond:'2', picId:'0181', isShow:'1', urlOut:'', words:'', EBWname:'シーフロアーソード・土', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0182', isShow:'1', urlOut:'', words:'', EBWname:'シーフロアーアクス・土', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0183', isShow:'1', urlOut:'', words:'', EBWname:'シーフロアーボウ・土', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0184', isShow:'1', urlOut:'', words:'', EBWname:'シーフロアースタッフ・土', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0185', isShow:'1', urlOut:'', words:'', EBWname:'シーフロアーハンマー・土', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0186', isShow:'1', urlOut:'', words:'', EBWname:'シーフロアースピア・土', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0187', isShow:'1', urlOut:'', words:'', EBWname:'フォーチュネイトソード・光', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0188', isShow:'1', urlOut:'', words:'', EBWname:'フォーチュネイトアクス・光', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0189', isShow:'1', urlOut:'', words:'', EBWname:'フォーチュネイトボウ・光', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0190', isShow:'1', urlOut:'', words:'', EBWname:'フォーチュネイトスタッフ・光', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0191', isShow:'1', urlOut:'', words:'', EBWname:'フォーチュネイトハンマー・光', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0192', isShow:'1', urlOut:'', words:'', EBWname:'フォーチュネイトスピア・光', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0193', isShow:'1', urlOut:'', words:'', EBWname:'プラニスフィアソード・雷', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0194', isShow:'1', urlOut:'', words:'', EBWname:'プラニスフィアアクス・雷', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0195', isShow:'1', urlOut:'', words:'', EBWname:'プラニスフィアボウ・雷', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0196', isShow:'1', urlOut:'', words:'', EBWname:'プラニスフィアスタッフ・雷', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0197', isShow:'1', urlOut:'', words:'', EBWname:'プラニスフィアハンマー・雷', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0198', isShow:'1', urlOut:'', words:'', EBWname:'プラニスフィアスピア・雷', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0199', isShow:'1', urlOut:'', words:'', EBWname:'アビサリアソード・氷', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0200', isShow:'1', urlOut:'', words:'', EBWname:'アビサリアアクス・氷', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0201', isShow:'1', urlOut:'', words:'', EBWname:'アビサリアボウ・氷', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0202', isShow:'1', urlOut:'', words:'', EBWname:'アビサリアスタッフ・氷', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0203', isShow:'1', urlOut:'', words:'', EBWname:'アビサリアハンマー・氷', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0204', isShow:'1', urlOut:'', words:'', EBWname:'アビサリアスピア・氷', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0205', isShow:'1', urlOut:'', words:'', EBWname:'鉱床の岩翼・剣・闇', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0206', isShow:'1', urlOut:'', words:'', EBWname:'鉱床の岩翼・斧・闇', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0207', isShow:'1', urlOut:'', words:'', EBWname:'鉱床の岩翼・弓矢・闇', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0208', isShow:'1', urlOut:'', words:'', EBWname:'鉱床の岩翼・杖・闇', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0209', isShow:'1', urlOut:'', words:'', EBWname:'鉱床の岩翼・ハンマー・闇', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0210', isShow:'1', urlOut:'', words:'', EBWname:'鉱床の岩翼・槍・闇', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0211', isShow:'1', urlOut:'', words:'', EBWname:'夕霧の剣', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0212', isShow:'1', urlOut:'', words:'', EBWname:'重霞のサイレントアクス', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0213', isShow:'1', urlOut:'', words:'', EBWname:'散虹のリグレットポウ', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0214', isShow:'1', urlOut:'', words:'', EBWname:'薄明の杖', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0215', isShow:'1', urlOut:'', words:'', EBWname:'望月の鎚', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0216', isShow:'1', urlOut:'', words:'', EBWname:'リュミエールランス', justWord:''},

    { kind:'newThings', kindSecond:'4', picId:'5097', isShow:'1', urlOut:'', words:'', EBWname:'生贄求めの司祭長', justWord:''},
    { kind:'newThings', kindSecond:'4', picId:'5098', isShow:'1', urlOut:'', words:'', EBWname:'ピッカリペッカー', justWord:''},
    { kind:'newThings', kindSecond:'4', picId:'5099', isShow:'1', urlOut:'', words:'', EBWname:'光空を泳ぐ者', justWord:''},
    { kind:'newThings', kindSecond:'4', picId:'5100', isShow:'1', urlOut:'', words:'', EBWname:'大波砕きの鉄拳', justWord:''},
    { kind:'newThings', kindSecond:'4', picId:'5101', isShow:'1', urlOut:'', words:'', EBWname:'水辺の竜鎧', justWord:''},
    { kind:'newThings', kindSecond:'4', picId:'5102', isShow:'1', urlOut:'', words:'', EBWname:'フラワリングペッカー', justWord:''},
    { kind:'newThings', kindSecond:'4', picId:'5103', isShow:'1', urlOut:'', words:'', EBWname:'群れ散らしの剛腕', justWord:''},
    { kind:'newThings', kindSecond:'4', picId:'5104', isShow:'1', urlOut:'', words:'', EBWname:'山賊の親玉', justWord:''},
    { kind:'newThings', kindSecond:'4', picId:'5105', isShow:'1', urlOut:'', words:'', EBWname:'重装型トライポッド', justWord:''},
    { kind:'newThings', kindSecond:'4', picId:'5106', isShow:'1', urlOut:'', words:'', EBWname:'シャルロットα', justWord:''},
    { kind:'newThings', kindSecond:'4', picId:'5107', isShow:'1', urlOut:'', words:'', EBWname:'シャルロットβ', justWord:''},
    { kind:'newThings', kindSecond:'4', picId:'5108', isShow:'1', urlOut:'', words:'', EBWname:'ダンケルクα', justWord:''},
    { kind:'newThings', kindSecond:'4', picId:'5109', isShow:'1', urlOut:'', words:'', EBWname:'ダンケルクβ', justWord:''},

    { kind:'newThings', kindSecond:'3', picId:'0024', isShow:'1', urlOut:'', words:'', EBWname:'ラウェハラの水面', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'0025', isShow:'1', urlOut:'', words:'', EBWname:'捧げよ!生贄求めの司祭長', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'1023', isShow:'1', urlOut:'', words:'', EBWname:'依頼と相場とメイド服', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'2022', isShow:'1', urlOut:'', words:'', EBWname:'巫女の笑顔', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'2023', isShow:'1', urlOut:'', words:'', EBWname:'深き眠りの工廠', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'3020', isShow:'1', urlOut:'', words:'', EBWname:'英雄の卵', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'3021', isShow:'1', urlOut:'', words:'', EBWname:'陰鬱なる廃坑', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'4024', isShow:'1', urlOut:'', words:'', EBWname:'切れ者', justWord:''},

    { kind:'nowActivity', kindSecond:'1', picId:'250001', isShow:'1', urlOut:'', words:'', EBWname:'', justWord:''},
    { kind:'nowActivity', kindSecond:'1', picId:'250002', isShow:'1', urlOut:'', words:'', EBWname:'', justWord:''},
    { kind:'nowActivity', kindSecond:'2', picId:'250003', isShow:'1', urlOut:'', words:'マンスリーイベント「こぼれ星に願いを」開催！', EBWname:'', justWord:''},

    { kind:'willThings', kindSecond:'1', picId:'230001', isShow:'1', urlOut:'https://www.bilibili.com/video/BV11x4y1Q7Tm', words:'【蓝色协议】第五章主线全剧情（人工熟肉+歌词翻译）', EBWname:'', justWord:''},
    { kind:'willThings', kindSecond:'1', picId:'230002', isShow:'1', urlOut:'https://www.bilibili.com/video/BV1Lw4m1Z7ZC', words:'【蓝色协议】爱抖露活动攻略', EBWname:'', justWord:''},
    { kind:'willThings', kindSecond:'1', picId:'230003', isShow:'1', urlOut:'https://www.bilibili.com/video/BV1zJ4m1a7b8', words:'【蓝色协议】第5章最新14个板子获取攻略', EBWname:'', justWord:''},
    { kind:'willThings', kindSecond:'1', picId:'230004', isShow:'1', urlOut:'https://www.bilibili.com/video/BV1t1421Z7vY', words:'【蓝色协议】通信#15-转播（同传熟肉）', EBWname:'', justWord:''},
]