////////////////////////////////////////
//   最近实装单位：newThings 新职业1 新武器2 新幻想e3 新幻想b4 新敌人5
//   情报：willThings   标题(words)     图     url链接(urlOut)    文字（justword）
//   当前活动：nowActivity 卡池1 活动主题图2
var G_value = [
    { kind:'newThings', kindSecond:'2', picId:'0295', isShow:'1', urlOut:'', words:'', EBWname:'ダグアップソード・土', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0296', isShow:'1', urlOut:'', words:'', EBWname:'ダグアップアクス・土', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0297', isShow:'1', urlOut:'', words:'', EBWname:'ダグアップボウ・土', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0298', isShow:'1', urlOut:'', words:'', EBWname:'ダグアップロッド・土', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0299', isShow:'1', urlOut:'', words:'', EBWname:'ダグアップハンマー・土', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0300', isShow:'1', urlOut:'', words:'', EBWname:'ダグアップスピア・土', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0301', isShow:'1', urlOut:'', words:'', EBWname:'ダグアップギター・土', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0302', isShow:'1', urlOut:'', words:'', EBWname:'ブルーメソード・雷', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0303', isShow:'1', urlOut:'', words:'', EBWname:'ブルーメアクス・雷', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0304', isShow:'1', urlOut:'', words:'', EBWname:'ブルーメボウ・雷', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0305', isShow:'1', urlOut:'', words:'', EBWname:'ブルーメロッド・雷', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0306', isShow:'1', urlOut:'', words:'', EBWname:'ブルーメハンマー・雷', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0307', isShow:'1', urlOut:'', words:'', EBWname:'ブルーメスピア・雷', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0308', isShow:'1', urlOut:'', words:'', EBWname:'ブルーメギター・雷', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0309', isShow:'1', urlOut:'', words:'', EBWname:'銀雪ノ剣', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0310', isShow:'1', urlOut:'', words:'', EBWname:'霰礫ノ斧', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0311', isShow:'1', urlOut:'', words:'', EBWname:'玉雪ノ弓', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0312', isShow:'1', urlOut:'', words:'', EBWname:'霜結ノ杖', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0313', isShow:'1', urlOut:'', words:'', EBWname:'雹砕ノ鎚', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0314', isShow:'1', urlOut:'', words:'', EBWname:'氷貫ノ槍', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'0315', isShow:'1', urlOut:'', words:'', EBWname:'六花ノ弦', justWord:''},

    { kind:'newThings', kindSecond:'4', picId:'5120', isShow:'1', urlOut:'', words:'', EBWname:'ハピハピウリボ', justWord:''},
    { kind:'newThings', kindSecond:'4', picId:'5121', isShow:'1', urlOut:'', words:'', EBWname:'キャプテンウリボ', justWord:''},
    { kind:'newThings', kindSecond:'4', picId:'5122', isShow:'1', urlOut:'', words:'', EBWname:'フレイム・ラピス', justWord:''},
    { kind:'newThings', kindSecond:'4', picId:'5123', isShow:'1', urlOut:'', words:'', EBWname:'血餓の闇夜狼', justWord:''},
    { kind:'newThings', kindSecond:'4', picId:'5124', isShow:'1', urlOut:'', words:'', EBWname:'黄昏の鬼人', justWord:''},
    { kind:'newThings', kindSecond:'4', picId:'5125', isShow:'1', urlOut:'', words:'', EBWname:'闇覗く大口', justWord:''},
    { kind:'newThings', kindSecond:'4', picId:'5126', isShow:'1', urlOut:'', words:'', EBWname:'宵巡りの猪', justWord:''},
    { kind:'newThings', kindSecond:'4', picId:'5127', isShow:'1', urlOut:'', words:'', EBWname:'アズールゴート', justWord:''},
    { kind:'newThings', kindSecond:'4', picId:'5128', isShow:'1', urlOut:'', words:'', EBWname:'白日の捕食者', justWord:''},
    { kind:'newThings', kindSecond:'4', picId:'5129', isShow:'1', urlOut:'', words:'', EBWname:'サニーナッポ', justWord:''},
    { kind:'newThings', kindSecond:'4', picId:'5130', isShow:'1', urlOut:'', words:'', EBWname:'終夜蜻蛉', justWord:''},
    { kind:'newThings', kindSecond:'4', picId:'5131', isShow:'1', urlOut:'', words:'', EBWname:'白昼の略奪者', justWord:''},

    { kind:'newThings', kindSecond:'3', picId:'0030', isShow:'1', urlOut:'', words:'', EBWname:'白日の捕食者は頂きに立つ', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'0031', isShow:'1', urlOut:'', words:'', EBWname:'噴火寸前フレイム・ラピス', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'0032', isShow:'1', urlOut:'', words:'', EBWname:'闇夜に蠢く黄昏の鬼人', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'0033', isShow:'1', urlOut:'', words:'', EBWname:'稼ぐのじゃ、下僕！', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'1029', isShow:'1', urlOut:'', words:'', EBWname:'神様からの贈り物', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'1030', isShow:'1', urlOut:'', words:'', EBWname:'強襲岩石、宵巡りの猪', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'1031', isShow:'1', urlOut:'', words:'', EBWname:'嘆きの剣舞ドラウグ・エッジ', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'1032', isShow:'1', urlOut:'', words:'', EBWname:'サニーナッポの生存術', justWord:''},

    { kind:'newThings', kindSecond:'3', picId:'2029', isShow:'1', urlOut:'', words:'', EBWname:'闇覗く大口の威迫', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'2030', isShow:'1', urlOut:'', words:'', EBWname:'哮り立つ血餓の闇夜狼', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'2031', isShow:'1', urlOut:'', words:'', EBWname:'最高の一杯を！', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'2032', isShow:'1', urlOut:'', words:'', EBWname:'財布と騎士の甲斐性', justWord:''},

    { kind:'newThings', kindSecond:'3', picId:'3027', isShow:'1', urlOut:'', words:'', EBWname:'砂漠の晩餐', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'3028', isShow:'1', urlOut:'', words:'', EBWname:'怪律音の終夜蜻蛉', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'3029', isShow:'1', urlOut:'', words:'', EBWname:'砂の潜伏者サンドバイパー', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'3030', isShow:'1', urlOut:'', words:'', EBWname:'聖堂の小さな声', justWord:''},

    { kind:'newThings', kindSecond:'3', picId:'4030', isShow:'1', urlOut:'', words:'', EBWname:'未来への道筋', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'4031', isShow:'1', urlOut:'', words:'', EBWname:'全力突進アズールゴート', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'4032', isShow:'1', urlOut:'', words:'', EBWname:'森に佇むポータル', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'4033', isShow:'1', urlOut:'', words:'', EBWname:'刺激厳禁ドゴルマン', justWord:''},

    { kind:'nowActivity', kindSecond:'1', picId:'250001', isShow:'1', urlOut:'', words:'', EBWname:'', justWord:''},
    { kind:'nowActivity', kindSecond:'1', picId:'250002', isShow:'1', urlOut:'', words:'', EBWname:'', justWord:''},
    { kind:'nowActivity', kindSecond:'1', picId:'250004', isShow:'1', urlOut:'', words:'', EBWname:'', justWord:''},
    { kind:'nowActivity', kindSecond:'2', picId:'250003', isShow:'1', urlOut:'', words:'マンスリーイベント「アステルリーズ開港祭」開催！', EBWname:'', justWord:''},

    { kind:'willThings', kindSecond:'1', picId:'230001', isShow:'1', urlOut:'https://www.bilibili.com/video/BV1fn4y197Ha', words:'『BLUE PROTOCOL』一周年PV', EBWname:'', justWord:''},
    { kind:'willThings', kindSecond:'1', picId:'230002', isShow:'1', urlOut:'https://www.bilibili.com/video/BV1in4y1Q7Nr', words:'【蓝色协议】一周年前瞻_通信#17', EBWname:'', justWord:''},
    { kind:'willThings', kindSecond:'1', picId:'230003', isShow:'1', urlOut:'https://www.bilibili.com/video/BV14S421d7oK', words:'【蓝色协议】周年庆版本攻略总集', EBWname:'', justWord:''},
    { kind:'willThings', kindSecond:'1', picId:'230004', isShow:'1', urlOut:'https://www.bilibili.com/video/BV1FS421o7xz', words:'【蓝色协议】新版本解包内容', EBWname:'', justWord:''},
]